// THE DEMO LIBRARY'S ASSETS, AND THIS FILE IS THE iOS ONE (proposal
// 2026-08-26-app-review-demo).
//
// The demo films ship in the Apple build only. Play caps the compressed download of an
// app bundle's base module at 200 MB and 164 MB of film on top of the app is past it,
// where Apple's 200 MB is only the point at which a cellular install asks first - and
// Apple is what forces the demo to exist at all (Guideline 2.1). So the exclusion is a
// BUILD RULE rather than a habit: Metro resolves `./demo-assets` to this file for iOS
// and to demo-assets.ts everywhere else, which exports nothing. Nothing here is
// referenced from an Android bundle, so nothing here is packaged into one.
//
// It cannot be an edit to `android/`: that tree is generated by `expo prebuild` and any
// change to it is gone at the next one (suite rule 5). test/demo-build-rule.test.js
// holds the two files to this, because the failure is silent until Play refuses an
// upload.
//
// THE REQUIRES ARE STATIC BECAUSE METRO'S ASSET GRAPH IS STATIC: the file names have to
// appear literally in the source or the media does not make it into the build. They
// must match assets/demo-library/manifest.json exactly - it is the key each one is
// resolved by at runtime.
//
// THE FILES ARE NOT IN THE REPO. `bash scripts/fetch-demo-films.sh` fetches, encodes
// and grabs the posters; without it an iOS bundle fails to resolve these modules, which
// is a loud failure at build time rather than a demo that browses and plays nothing.
//
// manifest.json is a SOURCE extension, so it arrives already parsed. The films and the
// posters are ASSET extensions, so they arrive as module handles the shell resolves to
// real paths at runtime.

/* eslint-disable @typescript-eslint/no-var-requires */
export const DEMO_MANIFEST = require('../assets/demo-library/manifest.json')

export const DEMO_FILES: Record<string, any> = {
  'Films/Duck and Cover (1951).mp4': require('../assets/demo-library/Films/Duck and Cover (1951).mp4'),
  'Films/A Trip Down Market Street (1906).mp4': require('../assets/demo-library/Films/A Trip Down Market Street (1906).mp4'),
  'TV Shows/The Apollo Missions/Season 01/The Apollo Missions - S01E01 - The Eagle Has Landed.mp4': require('../assets/demo-library/TV Shows/The Apollo Missions/Season 01/The Apollo Missions - S01E01 - The Eagle Has Landed.mp4'),
  'TV Shows/The Apollo Missions/Season 01/The Apollo Missions - S01E02 - Houston, We\'ve Got A Problem.mp4': require('../assets/demo-library/TV Shows/The Apollo Missions/Season 01/The Apollo Missions - S01E02 - Houston, We\'ve Got A Problem.mp4')
}

// THE ONE CAPTION FILE, and it is ours: written from the footage of a silent film, so
// nobody else's caption file is inherited along with it (assets/demo-library/LICENCES.md).
// It IS in the repo, unlike the films - the fetch script can reproduce a download, not a
// piece of writing.
export const DEMO_SUBTITLES: Record<string, any> = {
  'Films/A Trip Down Market Street (1906).en.srt': require('../assets/demo-library/Films/A Trip Down Market Street (1906).en.srt')
}

// NOT .jpg. A recognised image extension becomes an Android drawable RESOURCE, which
// expo-asset can only name and never resolve to a readable path - PearTune's first demo
// build failed exactly there. The bytes are ordinary JPEG.
export const DEMO_POSTERS: Record<string, any> = {
  'Films/Duck and Cover (1951).bin': require('../assets/demo-library/Films/Duck and Cover (1951).bin'),
  'Films/A Trip Down Market Street (1906).bin': require('../assets/demo-library/Films/A Trip Down Market Street (1906).bin'),
  'TV Shows/The Apollo Missions/poster.bin': require('../assets/demo-library/TV Shows/The Apollo Missions/poster.bin')
}
