'use strict'

// THE DEMO SHIPS ON iOS ONLY, AND THE FAILURE MODE IS SILENT (proposal
// 2026-08-26-app-review-demo, open question 3, decided 2026-08-26).
//
// Play caps the compressed download of an app bundle's base module at 200 MB, and
// 164 MB of film on top of the app is past it - where Apple's 200 MB is only the point
// at which a cellular install asks first. Nothing about an .mp4 in assets/ excludes
// itself from a build: the films ship in BOTH unless something deliberately stops them,
// and nobody finds out until Play refuses an upload.
//
// The exclusion is Metro's platform resolution: shell/demo-assets.ios.ts holds the
// requires, shell/demo-assets.ts holds none, and an Android bundle therefore references
// no film. It cannot be an edit to `android/` - that tree is generated by
// `expo prebuild` and any change to it is gone at the next one (suite rule 5).
//
// So this file guards the three things that make the rule true, in the only place a
// test can reach them: the source. What it cannot check is the built artefact, which
// needs a Metro run - `scripts/ios-sim-build.sh` is where a missing film shows up as a
// failed resolve, loudly, which is the other half.

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8')

const manifest = JSON.parse(read('assets/demo-library/manifest.json'))
const iosAssets = read('shell/demo-assets.ios.ts')
const otherAssets = read('shell/demo-assets.ts')

const films = manifest.films.map((f) => f.file)
  .concat(manifest.shows.flatMap((s) => s.episodes.map((e) => e.file)))
const posters = manifest.films.map((f) => f.poster).filter(Boolean)
  .concat(manifest.shows.map((s) => s.poster).filter(Boolean))

test('THE ANDROID SIDE REFERENCES NO FILM AT ALL', () => {
  assert.ok(!/demo-library/.test(otherAssets), 'shell/demo-assets.ts must not require anything from assets/demo-library')
  assert.ok(!/\.mp4/.test(otherAssets), 'a film in shell/demo-assets.ts would be packaged into the Android bundle')
  assert.match(otherAssets, /DEMO_FILES[^=]*=\s*\{\}/)
  assert.match(otherAssets, /DEMO_POSTERS[^=]*=\s*\{\}/)
  assert.match(otherAssets, /DEMO_MANIFEST[^=]*=\s*null/)
})

test('the iOS side lists exactly what the manifest names, by the same keys', () => {
  // METRO'S ASSET GRAPH IS STATIC: a name that does not appear literally in the source
  // is not in the build, and a key that does not match the manifest is a film the
  // worklet cannot resolve - which browses fine and plays nothing.
  // An apostrophe in a title arrives escaped in a single-quoted JS string, so compare
  // in the source's own form rather than the manifest's - Houston, We've Got A Problem
  // is the file that finds this out.
  const inSource = (name) => iosAssets.includes(name.replace(/'/g, "\\'"))
  for (const f of films) assert.ok(inSource(f), `shell/demo-assets.ios.ts is missing ${f}`)
  for (const p of posters) assert.ok(inSource(p), `shell/demo-assets.ios.ts is missing ${p}`)

  const listed = [...iosAssets.matchAll(/demo-library\/((?:[^'\\]|\\.)+)'\)/g)]
    .map((m) => m[1].replace(/\\'/g, "'"))
  for (const name of listed) {
    if (name === 'manifest.json') continue
    assert.ok(
      films.includes(name) || posters.includes(name),
      `${name} is required by the iOS build and is not in the manifest`
    )
  }
})

test('the fetch script produces exactly the files the manifest names', () => {
  const script = read('scripts/fetch-demo-films.sh')
  for (const f of films) assert.ok(script.includes(f), `scripts/fetch-demo-films.sh does not produce ${f}`)
  for (const p of posters) assert.ok(script.includes(p), `scripts/fetch-demo-films.sh does not produce ${p}`)
})

test('every film is direct-playable, because demo mode has no host to remux with', () => {
  const leaves = manifest.films.concat(manifest.shows.flatMap((s) => s.episodes))
  for (const l of leaves) {
    assert.equal(l.media.container, 'mp4', `${l.file} must be MP4`)
    assert.equal(l.media.videoCodec, 'h264', `${l.file} must be H.264`)
    // A silent film is allowed a null audio codec. Anything else has to be AAC.
    assert.ok(l.media.audioCodec === null || l.media.audioCodec === 'aac', `${l.file} must be AAC or silent`)
    assert.match(l.file, /\.mp4$/)
  }
})

test('the posters are not named as images, or Android cannot open them', () => {
  // A recognised image extension becomes an Android drawable RESOURCE, which expo-asset
  // can only name and never resolve to a path. PearTune's first demo build failed
  // exactly there. The films are excluded from Android, but the rule is about the
  // packager rather than the platform, and a .jpg here is a trap laid for later.
  for (const p of posters) assert.match(p, /\.bin$/)
  assert.ok(/assetExts\.push\('bin'\)/.test(read('metro.config.js')), "metro.config.js must treat .bin as an asset")
})

test('every shipped file is accounted for in the licence evidence', () => {
  const licences = read('assets/demo-library/LICENCES.md')
  // By title rather than by path: LICENCES.md is written for a person reading it, and
  // names the item and its identifier rather than the encoded output.
  for (const f of manifest.films) assert.ok(licences.includes(f.title), `LICENCES.md does not cover ${f.title}`)
  for (const s of manifest.shows) {
    for (const e of s.episodes) assert.ok(licences.includes(e.title), `LICENCES.md does not cover ${e.title}`)
  }
})
