// HLS FOR THE PHONE: how a codec the device cannot decode still plays there.
//
// The approved remux proposal specified the wire shape (media.playlist and
// media.segment, capabilities on the request, THE HOST DECIDES) and warned that
// the hard part is seeking, because generated bytes have no stable offsets. The
// browser got the pipe-and-restart answer; a phone's native player cannot be
// driven that way - ExoPlayer seeks HLS by SEGMENT, which is exact.
//
// The design that keeps every recorded constraint at once:
//
//   - THE PLAYLIST IS ARITHMETIC, NOT A FILE. Runtime over segment length gives
//     the segment count; the playlist is computed on request and nothing is
//     stored. A VOD playlist covering the whole film is what makes ExoPlayer's
//     scrubber work end to end.
//   - SEGMENTS ARE MADE ON DEMAND, one ffmpeg run per request, seeked precisely
//     (re-encode, so -ss is exact - the copy-snaps-to-keyframe trap does not
//     apply, because this path only ever runs when the codec must change anyway).
//     A phone that never seeks costs one 4-second encode per 4 seconds; the
//     measured engine does that at ~7x realtime.
//   - NOTHING IS WRITTEN TO DISK. Segment bytes go down the wire and are gone -
//     the remux proposal's hardest constraint (a cache the size of the film on a
//     box whose internal disk is small) disappears rather than being managed,
//     the same move the browser pipe made.
//   - THE ENGINE'S CAP IS THE GUARD. Segments run through the same Transcoder
//     pool as the browser's streams, so a phone cannot melt the box that four
//     concurrent browser viewers could not.
//
// PHONES ALMOST NEVER NEED REMUX: ExoPlayer opens Matroska and AVI natively, so
// the container problem that defined the browser's path barely exists here. This
// path is for CODEC misses - the HEVC a particular chip refuses (measured on the
// TCL, 2026-08-14: MediaCodec 0x80000000) - which is exactly the transcode case.

const SEGMENT_SECONDS = 4

// The whole playlist, from the item's runtime. `#EXT-X-PLAYLIST-TYPE:VOD` plus
// every segment named by index is what makes the duration bar and the scrubber
// real on the player's side.
function playlistFor (item, { base = '' } = {}) {
  const runtime = Number(item?.runtime) || 0
  if (runtime <= 0) return null

  const n = Math.ceil(runtime / SEGMENT_SECONDS)
  const lines = [
    '#EXTM3U',
    '#EXT-X-VERSION:3',
    `#EXT-X-TARGETDURATION:${SEGMENT_SECONDS}`,
    '#EXT-X-MEDIA-SEQUENCE:0',
    '#EXT-X-PLAYLIST-TYPE:VOD'
  ]
  for (let k = 0; k < n; k++) {
    const dur = k === n - 1 ? Math.max(0.001, runtime - k * SEGMENT_SECONDS) : SEGMENT_SECONDS
    lines.push(`#EXTINF:${dur.toFixed(3)},`)
    lines.push(`${base}${k}.ts`)
  }
  lines.push('#EXT-X-ENDLIST')
  return lines.join('\n') + '\n'
}

// How many segments a runtime yields - the route's bound check, kept beside the
// playlist arithmetic so the two cannot disagree.
function segmentCount (runtimeSeconds) {
  const runtime = Number(runtimeSeconds) || 0
  return runtime > 0 ? Math.ceil(runtime / SEGMENT_SECONDS) : 0
}

// The ffmpeg argv for ONE segment: seek precisely, encode exactly one segment's
// worth on the engine, emit MPEG-TS to the pipe with timestamps offset to the
// segment's place in the film - which is what lets the player stitch independent
// runs into one continuous stream.
function segmentArgs ({ input, headers = null, seq, media = {}, device, hwDecode, bitrate }) {
  const at = seq * SEGMENT_SECONDS
  const args = ['-hide_banner', '-loglevel', 'error', '-nostdin']

  if (headers) args.push('-headers', Object.entries(headers).map(([k, v]) => `${k}: ${v}\r\n`).join(''))

  if (hwDecode) args.push('-hwaccel', 'vaapi', '-hwaccel_device', device, '-hwaccel_output_format', 'vaapi')
  else args.push('-vaapi_device', device)

  if (at > 0) args.push('-ss', String(at))
  args.push('-t', String(SEGMENT_SECONDS))
  args.push('-i', input)
  args.push('-map', '0:v:0', '-map', '0:a:0?')
  args.push('-map_chapters', '-1')
  args.push('-vf', hwDecode ? 'scale_vaapi=format=nv12' : 'format=nv12,hwupload')
  args.push('-c:v', 'h264_vaapi', '-b:v', bitrate)
  // The soundtrack is always rebuilt on this path: TS + AAC is the least
  // surprising pairing for every HLS demuxer, and audio is a rounding error
  // beside the video encode already being paid.
  args.push('-c:a', 'aac', '-b:a', '192k', '-ac', '2')
  args.push('-sn', '-dn')
  // Timestamps continue from the segment's true position, so the player's clock
  // and the film agree across independently-generated segments.
  args.push('-output_ts_offset', String(at))
  args.push('-muxdelay', '0')
  args.push('-f', 'mpegts', 'pipe:1')
  return args
}

module.exports = { playlistFor, segmentCount, segmentArgs, SEGMENT_SECONDS }
