// HLS FOR THE PHONE: how a codec the device cannot decode still plays there.
//
// The approved remux proposal specified the wire shape (media.playlist and
// media.segment, capabilities on the request, THE HOST DECIDES) and warned that
// the hard part is seeking, because generated bytes have no stable offsets. The
// browser got the pipe-and-restart answer; a phone's native player cannot be
// driven that way - ExoPlayer seeks HLS by SEGMENT, which is exact.
//
// The design that keeps every recorded constraint at once:
//
//   - THE PLAYLIST IS ARITHMETIC, NOT A FILE. Runtime over segment length gives
//     the segment count; the playlist is computed on request and nothing is
//     stored. A VOD playlist covering the whole film is what makes ExoPlayer's
//     scrubber work end to end.
//   - SEGMENTS ARE MADE ON DEMAND, one ffmpeg run per request, seeked precisely
//     (re-encode, so -ss is exact - the copy-snaps-to-keyframe trap does not
//     apply, because this path only ever runs when the codec must change anyway).
//     A phone that never seeks costs one 4-second encode per 4 seconds; the
//     measured engine does that at ~7x realtime.
//   - NOTHING IS WRITTEN TO DISK. Segment bytes go down the wire and are gone -
//     the remux proposal's hardest constraint (a cache the size of the film on a
//     box whose internal disk is small) disappears rather than being managed,
//     the same move the browser pipe made.
//   - THE ENGINE'S CAP IS THE GUARD. Segments run through the same Transcoder
//     pool as the browser's streams, so a phone cannot melt the box that four
//     concurrent browser viewers could not.
//
// PHONES ALMOST NEVER NEED REMUX: ExoPlayer opens Matroska and AVI natively, so
// the container problem that defined the browser's path barely exists here. This
// path is for CODEC misses - the HEVC a particular chip refuses (measured on the
// TCL, 2026-08-14: MediaCodec 0x80000000) - which is exactly the transcode case.

const SEGMENT_SECONDS = 4

// The whole playlist, from the item's runtime. `#EXT-X-PLAYLIST-TYPE:VOD` plus
// every segment named by index is what makes the duration bar and the scrubber
// real on the player's side.
function playlistFor (item, { base = '' } = {}) {
  const runtime = Number(item?.runtime) || 0
  if (runtime <= 0) return null

  const n = Math.ceil(runtime / SEGMENT_SECONDS)
  const lines = [
    '#EXTM3U',
    '#EXT-X-VERSION:3',
    `#EXT-X-TARGETDURATION:${SEGMENT_SECONDS}`,
    '#EXT-X-MEDIA-SEQUENCE:0',
    '#EXT-X-PLAYLIST-TYPE:VOD'
  ]
  for (let k = 0; k < n; k++) {
    const dur = k === n - 1 ? Math.max(0.001, runtime - k * SEGMENT_SECONDS) : SEGMENT_SECONDS
    lines.push(`#EXTINF:${dur.toFixed(3)},`)
    lines.push(`${base}${k}.ts`)
  }
  lines.push('#EXT-X-ENDLIST')
  return lines.join('\n') + '\n'
}

// How many segments a runtime yields - the route's bound check, kept beside the
// playlist arithmetic so the two cannot disagree.
function segmentCount (runtimeSeconds) {
  const runtime = Number(runtimeSeconds) || 0
  return runtime > 0 ? Math.ceil(runtime / SEGMENT_SECONDS) : 0
}

// The ffmpeg argv for ONE segment: seek precisely, encode exactly one segment's
// worth on the engine, emit MPEG-TS to the pipe with timestamps offset to the
// segment's place in the film - which is what lets the player stitch independent
// runs into one continuous stream.
// The tone filters the 35mm skin can ask for. A LOOKUP, so a client string
// can only ever select one of these two graphs and never becomes argv.
const TONES = {
  bw: 'hue=s=0',
  sepia: 'colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131'
}

function segmentArgs ({ input, headers = null, seq, media = {}, device, hwDecode, bitrate, burn = null, tone = null }) {
  const at = seq * SEGMENT_SECONDS
  const args = ['-hide_banner', '-loglevel', 'error', '-nostdin']

  if (headers) args.push('-headers', Object.entries(headers).map(([k, v]) => `${k}: ${v}\r\n`).join(''))

  // BURN-IN DECODES IN SOFTWARE, deliberately (DECISIONS 2026-08-15). The
  // engine's own compositor (overlay_vaapi) is a third faster and SEGFAULTS on
  // real discs when the PGS stream changes composition size mid-stream - two
  // of four seek offsets died on A New Hope. The software graph held 4.85x
  // realtime single and 5.8x aggregate at four concurrent, stable everywhere,
  // and the encode stays on the engine either way.
  // A tone is a software filter, so it takes the software-decode lane the
  // same way burning does.
  const toneStep = TONES[tone] ? TONES[tone] + ',' : ''
  if (burn || toneStep) args.push('-vaapi_device', device)
  else if (hwDecode) args.push('-hwaccel', 'vaapi', '-hwaccel_device', device, '-hwaccel_output_format', 'vaapi')
  else args.push('-vaapi_device', device)

  if (at > 0) args.push('-ss', String(at))
  args.push('-t', String(SEGMENT_SECONDS))
  args.push('-i', input)
  if (burn) {
    // `burnIndex` counts WITHIN the subtitle streams - `[0:s:N]` - the same
    // vocabulary probe.js records and extractSubtitle maps by, and the PR #18
    // trap in reverse: this index would be off by two as an absolute `[0:N]`.
    //
    // THE PAD IS WHERE THE TEXT LIVES. Discs author PGS onto the full frame -
    // 1920x1080 - and put dialogue in the letterbox bar; a scope rip has the
    // bars CROPPED, so overlaying canvas on picture clips the text at the
    // picture's bottom edge (seen on the TCL, A New Hope at 1920x816: the top
    // halves of letters at the frame line). Restoring the frame around the
    // picture puts the text back in the bar the disc meant it for. The canvas
    // size rides from the probe when known; 1920x1080 otherwise, which is
    // what HD discs author against.
    const vw = Number(media?.width) || 0
    const vh = Number(media?.height) || 0
    const cw = Math.max(Number(burn.canvasWidth) || 1920, vw)
    const ch = Math.max(Number(burn.canvasHeight) || 1080, vh)
    const pad = vw && vh && (cw > vw || ch > vh)
      ? `pad=${cw}:${ch}:(ow-iw)/2:(oh-ih)/2[p];[p]`
      : ''
    args.push('-filter_complex', `[0:v:0]${pad}[0:s:${Number(burn.index)}]overlay[ov];[ov]${toneStep}format=nv12,hwupload[out]`)
    args.push('-map', '[out]', '-map', '0:a:0?')
  } else {
    args.push('-map', '0:v:0', '-map', '0:a:0?')
  }
  args.push('-map_chapters', '-1')
  if (!burn) {
    args.push('-vf', toneStep
      ? toneStep + 'format=nv12,hwupload'
      : (hwDecode ? 'scale_vaapi=format=nv12' : 'format=nv12,hwupload'))
  }
  args.push('-c:v', 'h264_vaapi', '-b:v', bitrate)
  // The soundtrack is always rebuilt on this path: TS + AAC is the least
  // surprising pairing for every HLS demuxer, and audio is a rounding error
  // beside the video encode already being paid.
  args.push('-c:a', 'aac', '-b:a', '192k', '-ac', '2')
  args.push('-sn', '-dn')
  // Timestamps continue from the segment's true position, so the player's clock
  // and the film agree across independently-generated segments.
  args.push('-output_ts_offset', String(at))
  args.push('-muxdelay', '0')
  args.push('-f', 'mpegts', 'pipe:1')
  return args
}

module.exports = { playlistFor, segmentCount, segmentArgs, TONES, SEGMENT_SECONDS }
