// HLS FOR THE PHONE: how a codec the device cannot decode still plays there.
//
// The approved remux proposal specified the wire shape (media.playlist and
// media.segment, capabilities on the request, THE HOST DECIDES) and warned that
// the hard part is seeking, because generated bytes have no stable offsets. The
// browser got the pipe-and-restart answer; a phone's native player cannot be
// driven that way - ExoPlayer seeks HLS by SEGMENT, which is exact.
//
// The design that keeps every recorded constraint at once:
//
//   - THE PLAYLIST IS ARITHMETIC, NOT A FILE. Runtime over segment length gives
//     the segment count; the playlist is computed on request and nothing is
//     stored. A VOD playlist covering the whole film is what makes ExoPlayer's
//     scrubber work end to end.
//   - SEGMENTS ARE MADE ON DEMAND, one ffmpeg run per request, seeked precisely
//     (re-encode, so -ss is exact - the copy-snaps-to-keyframe trap does not
//     apply, because this path only ever runs when the codec must change anyway).
//     A phone that never seeks costs one 4-second encode per 4 seconds; the
//     measured engine does that at ~7x realtime.
//   - NOTHING IS WRITTEN TO DISK. Segment bytes go down the wire and are gone -
//     the remux proposal's hardest constraint (a cache the size of the film on a
//     box whose internal disk is small) disappears rather than being managed,
//     the same move the browser pipe made.
//   - THE ENGINE'S CAP IS THE GUARD. Segments run through the same Transcoder
//     pool as the browser's streams, so a phone cannot melt the box that four
//     concurrent browser viewers could not.
//
// PHONES ALMOST NEVER NEED REMUX: ExoPlayer opens Matroska and AVI natively, so
// the container problem that defined the browser's path barely exists here. This
// path is for CODEC misses - the HEVC a particular chip refuses (measured on the
// TCL, 2026-08-14: MediaCodec 0x80000000) - which is exactly the transcode case.

// A SECOND ENGINE ON THE SAME PATH, added 2026-08-19. Everything above describes
// re-encoding, which was the only reason to segment a film when this file was
// written. It is no longer: a Roku refuses an unbounded progressive stream
// ("Full-content response on a range request: 200", its own words), so a REMUX has
// to reach it in segments too - and re-encoding a picture that was already perfect
// to get them would burn a full hardware transcode for nothing.
//
// So the playlist and the segment argv are now built from a PLAN rather than from
// arithmetic, and there are two ways to make one:
//
//   gridPlan   even SEGMENT_SECONDS steps. What a re-encode uses, because an
//              encode can cut anywhere and `-ss` is exact.
//   copyPlan   the film's own keyframes, from host/keyframes.js. What a copy must
//              use, because a copied picture cannot be cut anywhere else.
//
// A copy plan's segments are UNEVEN by nature - measured across two real films they
// run 4.0 s to 14.0 s against a 4 s target, because keyframes land on scene cuts.
// That is why the playlist takes its `#EXTINF` values from the plan instead of
// assuming them, and why `boundaries` travels back to the caller: a cast resuming
// mid-film has to snap to a real cut point rather than to a multiple of four.

const { VAAPI, engineFor } = require('./engines')

const SEGMENT_SECONDS = 4

// HOW FAR INTO A KEYFRAME'S OWN GROUP TO AIM `-ss`, and the single most surprising
// thing measured while building this. ffmpeg's backward seek lands on the keyframe
// STRICTLY BEFORE the requested time, so asking for a keyframe's exact timestamp
// hands back the one before it. Bisected on the test episode at eight points spread
// across the film: it needs between 0.130 and 0.136 seconds of headroom, stable
// everywhere. 0.30 s is a wide margin over that and still far inside the shortest
// keyframe gap measured in a real library (0.661 s).
const SEEK_HEADROOM = 0.30

// A keyframe with less than this before the next one cannot be aimed at safely, so
// it is not offered as a cut point. Nothing in the measured library comes close to
// tripping it; it exists so that a file which does degrades by choosing a different
// cut rather than by producing a broken segment.
const MIN_GROUP_SECONDS = SEEK_HEADROOM + 0.10

// One extra millisecond off the decode-order end, because `-to` includes the packet
// AT the limit. Without it the keyframe that opens the next segment also closes this
// one, and the frame count across the film comes out one high per join.
const CUT_EPSILON = 0.001

// A plan is { starts, seeks, ends, runtime, engine }: where each segment begins in
// the film, what to hand `-ss`, what to hand `-to`, and which engine made it. A
// grid plan needs neither seeks nor ends, because `-ss`/`-t` on a re-encode are
// exact - those stay null and segmentArgs keeps its original arithmetic.
function gridPlan (runtimeSeconds) {
  const runtime = Number(runtimeSeconds) || 0
  if (runtime <= 0) return null
  const starts = []
  for (let at = 0; at < runtime; at += SEGMENT_SECONDS) starts.push(at)
  return { engine: 'encode', starts, seeks: null, ends: null, runtime }
}

// The keyframe walk: from each boundary, the first keyframe at least
// SEGMENT_SECONDS later that has room to be aimed at. `times` is the film's
// keyframe list in seconds, in order, as host/keyframes.js returns it.
function copyPlan (times, { runtime, reorderDelay = 0, target = SEGMENT_SECONDS } = {}) {
  const total = Number(runtime) || 0
  if (!Array.isArray(times) || times.length < 2 || total <= 0) return null

  const starts = []
  const seeks = []
  for (let i = 0; i < times.length; i++) {
    const t = times[i]
    if (t >= total) break
    // The last keyframe's group runs to the end of the film. Without this it
    // could never be a cut point at all, and the closing segment would carry an
    // extra group of pictures for no reason.
    const group = (i + 1 < times.length ? times[i + 1] : total) - t
    if (group < MIN_GROUP_SECONDS) continue
    if (starts.length && t - starts[starts.length - 1] < target) continue
    starts.push(t)
    // Aim inside the group, never at its edge. Half a group when the group is
    // short, so a 0.7 s group is still aimed at with room on both sides.
    seeks.push(t + Math.min(SEEK_HEADROOM, group / 2))
  }
  if (starts.length < 2) return null

  // THE FILM BEGINS AT ZERO, whatever its first keyframe's timestamp says. Two of
  // three real films measured start theirs a few hundredths of a second in, and the
  // opening segment is the one that is never seeked - it runs from the file's true
  // beginning - so claiming its own keyframe's time would understate the film by
  // exactly that much and shift every later position report by it.
  starts[0] = 0

  // A segment ends where the next one begins, in DECODE order - which is the next
  // keyframe's presentation time less the reorder delay. The last one runs to the
  // end of the film and needs no correction.
  const ends = starts.map((_, k) => k + 1 < starts.length
    ? starts[k + 1] - reorderDelay - CUT_EPSILON
    : total)

  return { engine: 'copy', starts, seeks, ends, runtime: total }
}

// The whole playlist, from a plan. `#EXT-X-PLAYLIST-TYPE:VOD` plus every segment
// named by index is what makes the duration bar and the scrubber real on the
// player's side, and the durations have to be the REAL ones: a Roku takes the
// film's length from the sum of these lines, measured 2026-08-19 (it reported
// 111924 ms for a playlist whose EXTINF values summed to 111.924 s).
function playlistFor (item, { base = '', plan = null } = {}) {
  const p = plan || gridPlan(item?.runtime)
  if (!p || !p.starts.length) return null

  const durations = durationsOf(p)
  const lines = [
    '#EXTM3U',
    '#EXT-X-VERSION:3',
    `#EXT-X-TARGETDURATION:${Math.max(1, Math.ceil(Math.max(...durations)))}`,
    '#EXT-X-MEDIA-SEQUENCE:0',
    '#EXT-X-PLAYLIST-TYPE:VOD'
  ]
  for (let k = 0; k < p.starts.length; k++) {
    lines.push(`#EXTINF:${durations[k].toFixed(3)},`)
    lines.push(`${base}${k}.ts`)
  }
  lines.push('#EXT-X-ENDLIST')
  return lines.join('\n') + '\n'
}

// Every segment's real length, the playlist's EXTINF values and the only honest
// answer to "how long is segment k".
function durationsOf (plan) {
  return plan.starts.map((start, k) => Math.max(
    0.001,
    (k + 1 < plan.starts.length ? plan.starts[k + 1] : plan.runtime) - start
  ))
}

// How many segments a plan yields - the route's bound check, kept beside the
// playlist so the two cannot disagree.
function segmentCount (runtimeOrPlan) {
  if (runtimeOrPlan && Array.isArray(runtimeOrPlan.starts)) return runtimeOrPlan.starts.length
  const runtime = Number(runtimeOrPlan) || 0
  return runtime > 0 ? Math.ceil(runtime / SEGMENT_SECONDS) : 0
}

// The ffmpeg argv for ONE segment: seek precisely, encode exactly one segment's
// worth on the engine, emit MPEG-TS to the pipe with timestamps offset to the
// segment's place in the film - which is what lets the player stitch independent
// runs into one continuous stream.
// The tone filters the 35mm skin can ask for. A LOOKUP, so a client string
// can only ever select one of these two graphs and never becomes argv.
const TONES = {
  bw: 'hue=s=0',
  sepia: 'colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131'
}

// What MPEG-TS will carry untouched. A soundtrack the client already accepts is
// still rebuilt when the segment container cannot hold it.
const TS_AUDIO = new Set(['aac', 'mp3', 'ac3', 'eac3'])

// The ffmpeg argv for ONE COPIED segment. The picture is not touched at all; only
// the soundtrack is rebuilt, which is what a remux already does to a pipe.
//
// THE FOUR FLAGS THAT MAKE THIS EXACT, each of them measured on 2026-08-19 against
// a real film, and each of them wrong to drop:
//
//   -copyts            keep the film's own timestamps, so `-to` is an absolute
//                      time in the film and the segment needs no offset faked onto
//                      it afterwards. Without it the numbers are relative to the
//                      seek and every arithmetic error compounds.
//   -noaccurate_seek   do not trim to the requested time. The requested time is
//                      deliberately INSIDE the group of pictures (see
//                      SEEK_HEADROOM), so trimming to it would drop the segment's
//                      first fifth of a second of sound.
//   -ss <seek>         aimed past the keyframe, never at it.
//   -to <end>          the next keyframe's decode time, less a millisecond.
//
// Verified on two films by counting: the segments hold every source frame in their
// span exactly once - 2,683 of 2,683 and 3,316 of 3,316, no overlap at any join,
// with the sound meeting within a millisecond.
// HOW MANY SPEAKERS TO ENCODE FOR, which is not simply the client's number. `-ac 6`
// against a STEREO source does not leave it alone, it UPMIXES - six channels of a two
// channel film, at six channels' worth of bitrate, for nothing. So the answer is the
// smaller of what the client takes and what the film actually has, and a film whose
// channel count is unknown is left at the client's number rather than guessed at.
function channelsFor (clientMax, sourceChannels) {
  const want = Number(clientMax) || 2
  const have = Number(sourceChannels) || 0
  return have ? Math.min(want, have) : want
}

function copySegmentArgs ({ input, headers = null, seq, plan, audio = 'aac', audioCodec = null, audioChannels = 2 }) {
  const args = ['-hide_banner', '-loglevel', 'error', '-nostdin']
  if (headers) args.push('-headers', Object.entries(headers).map(([k, v]) => `${k}: ${v}\r\n`).join(''))

  args.push('-copyts', '-noaccurate_seek')
  // The first segment starts at the film's own beginning, so it is not seeked at
  // all - there is no keyframe before zero to fall back onto.
  if (seq > 0) args.push('-ss', plan.seeks[seq].toFixed(6))
  args.push('-i', input)
  args.push('-to', plan.ends[seq].toFixed(6))

  args.push('-map', '0:v:0', '-map', '0:a:0?', '-map_chapters', '-1')
  args.push('-c:v', 'copy')
  if (audio === 'copy' && TS_AUDIO.has(String(audioCodec || '').toLowerCase())) {
    args.push('-c:a', 'copy')
  } else {
    args.push('-c:a', 'aac', '-b:a', '192k', '-ac', String(Math.max(1, Number(audioChannels) || 2)))
  }
  args.push('-sn', '-dn')
  // The muxer's own 1.4 s preload would shift every segment's clock off the film's,
  // and negative-timestamp shifting would undo -copyts on the first segment.
  args.push('-avoid_negative_ts', 'disabled', '-muxdelay', '0', '-muxpreload', '0')
  args.push('-f', 'mpegts', 'pipe:1')
  return args
}

function segmentArgs ({ input, headers = null, seq, media = {}, device, hwDecode, bitrate, burn = null, tone = null, plan = null, audioChannels = 2, engine = null }) {
  const at = plan?.starts ? plan.starts[seq] : seq * SEGMENT_SECONDS
  const length = plan?.starts
    ? (seq + 1 < plan.starts.length ? plan.starts[seq + 1] : plan.runtime) - at
    : SEGMENT_SECONDS
  const args = ['-hide_banner', '-loglevel', 'error', '-nostdin']

  if (headers) args.push('-headers', Object.entries(headers).map(([k, v]) => `${k}: ${v}\r\n`).join(''))

  // BURN-IN DECODES IN SOFTWARE, deliberately (DECISIONS 2026-08-15). The
  // engine's own compositor (overlay_vaapi) is a third faster and SEGFAULTS on
  // real discs when the PGS stream changes composition size mid-stream - two
  // of four seek offsets died on A New Hope. The software graph held 4.85x
  // realtime single and 5.8x aggregate at four concurrent, stable everywhere,
  // and the encode stays on the engine either way.
  // A tone is a software filter, so it takes the software-decode lane the
  // same way burning does.
  const toneStep = TONES[tone] ? TONES[tone] + ',' : ''
  // WHOSE CARD THIS IS. The graph above is the same on any vendor; what differs is how
  // the decoder is named and what the encoder wants handed to it, and those four
  // answers live in engines.js. Absent means VAAPI, which is what every install ran on
  // before there was a choice.
  const eng = (typeof engine === 'string' ? engineFor(engine) : engine) || VAAPI
  args.push(...eng.inputArgs({ device, software: !!burn || !!toneStep || !hwDecode }))

  if (at > 0) args.push('-ss', String(at))
  args.push('-t', String(length))
  args.push('-i', input)
  if (burn) {
    // `burnIndex` counts WITHIN the subtitle streams - `[0:s:N]` - the same
    // vocabulary probe.js records and extractSubtitle maps by, and the PR #18
    // trap in reverse: this index would be off by two as an absolute `[0:N]`.
    //
    // THE PAD IS WHERE THE TEXT LIVES. Discs author PGS onto the full frame -
    // 1920x1080 - and put dialogue in the letterbox bar; a scope rip has the
    // bars CROPPED, so overlaying canvas on picture clips the text at the
    // picture's bottom edge (seen on the TCL, A New Hope at 1920x816: the top
    // halves of letters at the frame line). Restoring the frame around the
    // picture puts the text back in the bar the disc meant it for. The canvas
    // size rides from the probe when known; 1920x1080 otherwise, which is
    // what HD discs author against.
    const vw = Number(media?.width) || 0
    const vh = Number(media?.height) || 0
    const cw = Math.max(Number(burn.canvasWidth) || 1920, vw)
    const ch = Math.max(Number(burn.canvasHeight) || 1080, vh)
    const pad = vw && vh && (cw > vw || ch > vh)
      ? `pad=${cw}:${ch}:(ow-iw)/2:(oh-ih)/2[p];[p]`
      : ''
    args.push('-filter_complex', `[0:v:0]${pad}[0:s:${Number(burn.index)}]overlay[ov];[ov]${toneStep}${eng.toEngine}[out]`)
    args.push('-map', '[out]', '-map', '0:a:0?')
  } else {
    args.push('-map', '0:v:0', '-map', '0:a:0?')
  }
  args.push('-map_chapters', '-1')
  if (!burn) {
    args.push('-vf', toneStep
      ? toneStep + eng.toEngine
      : (hwDecode ? eng.fromHwDecode : eng.toEngine))
  }
  args.push('-c:v', eng.encoder, ...eng.encoderArgs(device), '-b:v', bitrate)
  // The soundtrack is always rebuilt on this path: TS + AAC is the least
  // surprising pairing for every HLS demuxer, and audio is a rounding error
  // beside the video encode already being paid. Rebuilt at the client's own speaker
  // count, though - a picture converted for a television it fits is no reason to take
  // that television's surround away.
  args.push('-c:a', 'aac', '-b:a', '192k', '-ac', String(Math.max(1, Number(audioChannels) || 2)))
  args.push('-sn', '-dn')
  // Timestamps continue from the segment's true position, so the player's clock
  // and the film agree across independently-generated segments.
  args.push('-output_ts_offset', String(at))
  args.push('-muxdelay', '0')
  args.push('-f', 'mpegts', 'pipe:1')
  return args
}

module.exports = {
  playlistFor,
  segmentCount,
  segmentArgs,
  copySegmentArgs,
  channelsFor,
  gridPlan,
  copyPlan,
  durationsOf,
  TONES,
  TS_AUDIO,
  SEGMENT_SECONDS,
  SEEK_HEADROOM,
  MIN_GROUP_SECONDS,
  CUT_EPSILON
}
