// Drives PearCinema on the iPhone Simulator so the App Review demo video can be recorded
// with nobody tapping (proposal 2026-08-26-app-review-demo, the video half).
//
// WHY A UI TEST AND NOT A SHELL SCRIPT. Driving the Simulator from OUTSIDE needs macOS
// Accessibility permission, which an ssh session cannot be granted without somebody
// sitting at the machine. XCUITest runs INSIDE the simulator via testmanagerd and needs
// no such grant, so this works headlessly over ssh - which is the whole point.
// Inherited from PearTune's driver, which learned all of that the expensive way.
//
// It attaches to the ALREADY-INSTALLED app by bundle id rather than being a target inside
// the PearCinema Xcode project. `ios/` is generated by `expo prebuild`, so a test target
// added there would vanish at the next regeneration; this project is standalone and
// outlives it.
//
// PACING IS DELIBERATE. Every step sleeps longer than it needs to. This is filmed, not
// asserted - a viewer has to be able to read the screen before it changes, and a cut that
// lands mid-transition looks like a glitch rather than a feature.

import XCTest

final class DemoFlow: XCTestCase {

  let app = XCUIApplication(bundleIdentifier: "com.pearcinema")

  override func setUp() {
    super.setUp()
    // Keep going after a miss so one run reports EVERY step that failed rather than the
    // first. Each helper dumps the hierarchy on a miss, so a single run says what changed.
    continueAfterFailure = true
  }

  // Wait for a button and tap it, then hold for the camera.
  private func tap (_ label: String, wait: TimeInterval = 25, hold: UInt32 = 3, line: UInt = #line) {
    let b = app.buttons[label]
    if !b.waitForExistence(timeout: wait) {
      XCTFail("no button '\(label)' after \(wait)s", line: line)
      print("=== HIERARCHY AT MISS (\(label)) ===\n\(app.debugDescription)\n=== END ===")
      return
    }
    b.tap()
    sleep(hold)
  }

  // Tap by position instead of by name.
  //
  // TWO KINDS OF THING NEED THIS, and neither is laziness. The film tiles are DIV-based
  // React nodes rather than <button>s, so accessibility publishes them as generic
  // elements with no stable label to address. The player's own controls are React Native
  // views drawn ABOVE the WebView, and the ones with no accessibilityLabel (the CC button
  // and the rows of its picker) cannot be reached any other way.
  //
  // The offsets below are for the device this is filmed on. A different screen size moves
  // them, which is what PlaybackProbe exists to re-measure.
  private func tapAt (_ dx: CGFloat, _ dy: CGFloat, hold: UInt32 = 3) {
    app.coordinate(withNormalizedOffset: CGVector(dx: dx, dy: dy)).tap()
    sleep(hold)
  }

  // THE SHOT. Cold launch -> named -> the demo library -> both trees -> a film playing,
  // with its captions on. No pairing, no host, no network at any point.
  func testRecordDemoFlow () {
    app.launch()
    sleep(18) // the Bare worklet boots, then the WebView loads its bundle

    // 1. The intro: what PearCinema even is.
    sleep(4)
    tap("Get started")

    // 2. Who is this? The name reaches the operator's dashboard on a real pair, and it is
    //    asked BEFORE the demo is offered so a demo user is never anonymous.
    let field = app.textFields.firstMatch
    if field.waitForExistence(timeout: 20) {
      field.tap()
      sleep(1)
      app.typeText("Alex")
      sleep(2)
      // The keyboard covers Continue. Tapping the heading dismisses it without changing
      // any state.
      tapAt(0.5, 0.18, hold: 2)
    } else {
      XCTFail("no name field")
      print("=== HIERARCHY AT MISS (name field) ===\n\(app.debugDescription)\n=== END ===")
    }
    tap("Continue")

    // 3. Whose library is it? Three honest answers, and a reviewer has neither of the
    //    first two. Straight apostrophe: it is what the UI renders.
    sleep(3)
    tap("I don't have one yet", hold: 2)

    // 4. The library appears. THIS IS THE BEAT THAT MATTERS - no pairing, no server, no
    //    network. Long hold: the banner across the top is the explanation.
    sleep(22)

    // 5. The shows half, because a library that is only a grid of films is half an app.
    //    Series -> its seasons, then back.
    tap("Shows", hold: 4)
    tapAt(0.26, 0.58, hold: 5)   // the show
    tap("Back to Shows", hold: 3)
    tap("Films", hold: 4)

    // 6. A film's own page: what the file is, how long it runs, and that it carries
    //    subtitles. Held long enough to read.
    tapAt(0.47, 0.58, hold: 8)   // A Trip Down Market Street, second in Recently added

    // 7. Play it.
    tap("Watch", hold: 14)

    // 8. Captions on. The controls fade, so the first tap brings them back; the second is
    //    the CC button; the third is the track in its picker. All three are positions -
    //    none of these carries a label to address.
    tapAt(0.5, 0.45, hold: 2)
    tapAt(0.92, 0.14, hold: 3)
    tapAt(0.29, 0.54, hold: 4)

    // 9. Let it run with the captions drawing over the picture.
    sleep(24)

    print("=== FLOW COMPLETE ===")
  }
}
