// The player.
//
// TWO WAYS TO GET A FILM, and the browser never chooses between them:
//
//   /api/stream  - the actual file, byte-ranged. Free, exact, and seekable by the
//                  native scrubber. Used whenever the browser will open the file.
//   /api/remux   - generated MP4 on the fly. Repackaged when the browser refuses the
//                  container, the soundtrack rebuilt when it cannot decode it, and -
//                  on a host whose hardware probe passed - the picture converted to
//                  H.264 on the video engine when the browser cannot decode THAT.
//                  The host decides which of those it is; to this player they are
//                  all the same stream.
//
// The HOST decides which. A client can describe itself and cannot demand to be
// repackaged, because direct play is free and exact and remux is neither.
//
// WHY THE SCRUBBER IS OURS ON A REPACKAGED FILM. Generated bytes have no stable byte
// offsets - there is no "byte 2.4 billion" until everything before it has been made -
// so a native <video> seek, which IS a byte-range request, cannot work. Instead the
// player asks the host to start again at a new time and adds that offset to the
// element's own clock. The cost is a moment's rebuffer on each seek. The alternative
// was a byte-to-time map faked from average bitrate, which is approximate on constant
// bitrate video and simply wrong on variable, which is most video.
//
// NOTHING FAILS SILENTLY. A file that cannot be played even repackaged says which
// part is the problem, and "Try anyway" is always offered, because canPlayType
// answers about a codec family rather than a file and can be wrong in both
// directions.

import { useState, useEffect, useRef } from 'preact/hooks'
import { api, withBase, fmtRuntime, fmtExact, fmtSize, fmtClock, episodeCode } from './api'
import { verdictFor, containerName, capabilityQuery } from './playback'
import Controls from './Controls'
import { Blocked, Check, Close, Info, Download as DownloadIcon, Trash } from './icons'

// HOW LONG THE CARD WAITS before the next episode starts itself. Ten seconds is
// Plex's, and it is the number to copy rather than improve on: long enough to
// read the title and reach the mouse, short enough that nobody sits through it.
const NEXT_SECONDS = 10

// The countdown dial's circumference, r=28 in a 64-wide box. Held here so the
// stroke maths and the SVG cannot drift apart.
const DIAL = 2 * Math.PI * 28

// AUTOPLAY IS A PREFERENCE OF THIS BROWSER, not of the library. It says what
// this person wants to happen while they are sitting in front of this screen,
// which is exactly the kind of thing localStorage is for - and it must not
// travel to somebody else's device on the same host (Tim, 2026-08-20).
// Absent means on.
const AUTOPLAY_KEY = 'pearcinema.autoplaynext'
function readAutoplay () {
  try { return localStorage.getItem(AUTOPLAY_KEY) !== 'off' } catch { return true }
}
function writeAutoplay (on) {
  try { localStorage.setItem(AUTOPLAY_KEY, on ? 'on' : 'off') } catch {}
}

export default function Player ({ item, caps, queue = [], onPlay, onClose, onUp = null, watch = null, onWatchChange = () => {}, remote = false }) {
  const [forced, setForced] = useState(false)
  const [subs, setSubs] = useState([])
  const [failed, setFailed] = useState(null)
  const [at, setAt] = useState(0)
  // Where the CURRENT repackaged stream begins. The element's own currentTime counts
  // from zero on every restart, so the clock the viewer sees is this plus that.
  const [offset, setOffset] = useState(0)
  const [busy, setBusy] = useState(false)
  // Non-null while the "you got to 42 minutes" card is up. NOTHING JUMPS ON ITS OWN:
  // somebody who opened a film to watch the beginning again should not have to scrub
  // backwards out of a resume they never asked for.
  const [offer, setOffer] = useState(null)
  const [seen, setSeen] = useState(false)
  // The details sheet. Shut by default and shut again on every new film - it is a
  // question somebody asked about THIS one.
  const [details, setDetails] = useState(false)
  // The episode on either side, walked across the whole show by the host. Null
  // until it answers, and two nulls for a film.
  const [sib, setSib] = useState(null)
  // PLAYING NEXT. `upNext` is the card being up; `left` is the countdown, and
  // null there means the card is up but nothing is going to happen on its own -
  // which is both what autoplay-off looks like and what cancelling leaves.
  const [upNext, setUpNext] = useState(false)
  const [left, setLeft] = useState(null)
  const [autoplay, setAutoplay] = useState(readAutoplay)
  const video = useRef(null)
  // HAS THE VIEWER ASKED FOR THIS TO PLAY? Nothing starts on its own (Tim,
  // 2026-08-13): opening a page should not fill a room with sound, and on a
  // repackaged film it also spends a child process on the host before anybody has
  // said they want it.
  //
  // It cannot simply be "no autoplay", though. On the repackaged path a SEEK is a new
  // stream and therefore a new element, so without this a scrub would silently stop
  // playback. The flag says the viewer already pressed play, and the new element picks
  // up where the old one left off.
  const wantPlay = useRef(false)
  // THE ONE CASE WHERE A NEW FILM MAY START ITSELF. `wantPlay` is cleared on
  // every new item on purpose - clicking a second film must not start it - but
  // the card at the end of an episode IS somebody saying play the next one, by
  // pressing it or by letting the countdown run out. This ref survives the item
  // change (the component is not remounted, only re-propped) and hands that
  // intent across (Tim, 2026-08-20: the browser moved to the next episode and
  // sat there paused, while the phone played it).
  const autoStart = useRef(false)
  // The last position WRITTEN, so the fifteen-second heartbeat can skip a write when
  // nothing has moved - a paused film should not keep writing the same number.
  const wrote = useRef(0)

  // THE KEPT COPY CHANGES THE VERDICT (desktop-client phase 2). A downloaded
  // film answers off this machine's own disk through the same routes, and for
  // a converted download what is IN the file is the mp4 the friend's hardware
  // made - not what the library says sits on their disk. So the verdict runs
  // against the download's own facts, and everything downstream (which route,
  // whose scrubber) falls out correctly. `dlTick` re-looks after start/cancel/
  // remove, and the poll keeps itself alive only while a download runs.
  const [dl, setDl] = useState(null)
  const [dlErr, setDlErr] = useState('')
  const [dlTick, setDlTick] = useState(0)
  // NOTHING STREAMS UNTIL THE KEPT COPY IS KNOWN. Rendering the video off the
  // LIBRARY's facts while the downloads answer was still in flight fired one
  // doomed request (the host judges a downloaded film by the kept file and
  // answered 409 to the guess), whose error banner then outlived the
  // recovery - Tim watched it stick to a downloaded episode until a refresh.
  // The downloads call is loopback-local; holding one beat costs nothing.
  const [dlKnown, setDlKnown] = useState(!remote)
  useEffect(() => {
    if (!remote) { setDl(null); setDlKnown(true); return }
    let live = true
    let t = null
    const look = async () => {
      const r = await api('/api/downloads')
      if (!live) return
      const row = (r.items || []).find(d => d.itemId === item.id) || null
      setDl(row)
      setDlKnown(true)
      if (row?.downloading) t = setTimeout(look, 2000)
    }
    look()
    return () => { live = false; clearTimeout(t) }
  }, [item.id, remote, dlTick])
  const kept = dl && !dl.downloading ? dl : null

  // The verdict changed sources (the download landed or was removed) - any
  // error the OLD stream earned is stale news for the new one.
  useEffect(() => { setFailed(null) }, [!!kept])

  const verdict = verdictFor(kept?.media ? { ...item, media: kept.media } : item, caps)
  // The browser can see the common case without a round trip: the container is
  // refused and the streams inside it are ones it can decode. The host still makes
  // the real decision and will answer 409 if it disagrees.
  // Repackage when it is the only way to play it AND when it is the only way to HEAR
  // it. A silent film is broken, and rebuilding a soundtrack is cheap - so a
  // 'nosound' verdict is fixed rather than merely reported.
  // A `convert` verdict streams through the same route: to the player, remux and
  // transcode are the same thing - generated MP4 down a socket, seek by restart.
  const remuxing = ((verdict.status === 'refuse' || verdict.status === 'nosound') && verdict.remuxable) ||
    verdict.status === 'convert' || forced
  const blocked = verdict.status === 'refuse' && !verdict.remuxable && !forced

  // SECONDS ALREADY. This used to multiply by 60, on the same misreading that showed
  // 300 as a 116-hour film - and it was worse here than in a label: the scrubber's
  // range was sixty times too long, so dragging it anywhere past the very start asked
  // the host to begin at a time beyond the end of the film. ffmpeg produced nothing,
  // the browser stalled, and playback stopped and would not resume. That is the
  // "sometimes pauses and will not start again" Tim reported.
  // SECONDS ALREADY - this used to multiply by 60, the same misreading that showed
  // 300 as a 116-hour film, and here it made the scrub bar's range sixty times too
  // long so every jump landed past the end of the film.
  //
  // `elDuration` is preferred when the element knows one, because for a file playing
  // straight from disk it is exact. A repackaged stream cannot report one at all -
  // its bytes are still being made - so there the library's own runtime is all there
  // is, and it is why the item model carrying a runtime matters more than it looks.
  const [elDuration, setElDuration] = useState(0)

  // The chosen image subtitle track being PRESSED into the picture by the host
  // (null = none). Burning is a re-encode, so an active burn takes the
  // generated-bytes route whatever the file could otherwise do, and a seek is
  // a restart exactly as it is for any remux.
  const [burnSub, setBurnSub] = useState(null)
  const generated = remuxing || !!burnSub

  const duration = (!generated && elDuration > 0 ? elDuration : item.runtime) || 0

  useEffect(() => {
    setForced(false); setFailed(null); setAt(0); setOffset(0); setSubs([]); setBusy(false)
    setOffer(null)
    setBurnSub(null)
    wrote.current = 0
    // A different film is a fresh decision. Playing one and clicking another must not
    // start the second one on its own - unless it arrived off the playing-next
    // card, which is that decision already made.
    wantPlay.current = autoStart.current
    autoStart.current = false
    setDetails(false)
    setSib(null); setUpNext(false); setLeft(null)
    let live = true
    api('/api/subtitles?itemId=' + encodeURIComponent(item.id)).then(res => {
      if (live) setSubs(res.items || [])
    })

    // The neighbours, asked once per episode. They drive Previous and Next and
    // they are what the card at the end offers - so this is asked for a film
    // too and simply comes back empty, rather than being branched on here.
    api('/api/siblings?itemId=' + encodeURIComponent(item.id))
      .then(res => { if (live && !res?.error) setSib(res) })
      .catch(() => {})

    // Where this person got to, from the shelf we already have rather than a second
    // round trip. `watch` is a snapshot from when the library last read it, which is
    // exactly right: it is what was true when they clicked.
    const prior = (watch?.continue || []).find(x => x.id === item.id)
    if (prior?.resume?.positionMs > 0) setOffer(prior.resume.positionMs / 1000)
    setSeen((watch?.watched || []).includes(item.id))

    return () => { live = false }
  }, [item.id])

  const src = withBase(generated
    ? '/api/remux?id=' + encodeURIComponent(item.id) + '&t=' + Math.floor(offset) + '&' + capabilityQuery(caps) +
      (burnSub ? '&burn=' + encodeURIComponent(burnSub) : '')
    : '/api/stream?id=' + encodeURIComponent(item.id))

  // ONE SEEK, and the controls above it cannot tell the difference.
  //
  // Playing from the file, the browser holds the whole thing and a seek is instant.
  // Repackaged, the bytes past this point do not exist yet, so a seek means asking
  // the host to start again from there - which costs a second and is the only thing
  // generated bytes allow.
  const seekTo = (seconds) => {
    const t = Math.max(0, duration ? Math.min(seconds, duration - 1) : seconds)
    setFailed(null)

    if (!generated && video.current) {
      video.current.currentTime = t
      setAt(t)
      return
    }

    setBusy(true); setOffset(t); setAt(t)
  }

  // TELL THE HOST WHERE WE ARE. Every fifteen seconds, on pause, and on the way out -
  // never on `timeupdate`, which fires four times a second and would be 28,800 writes
  // across a two-hour film.
  //
  // The host decides what the number MEANS: whether it counts as started, whether it
  // counts as finished, and what to do with a position past the end of a file that has
  // been re-encoded since. None of that is decided here, because the phone will need
  // the same answers and two copies of the rule is one copy that drifts.
  const savePosition = async (ended = false) => {
    const ms = Math.round(at * 1000)
    if (!ended && Math.abs(ms - wrote.current) < 5000) return
    wrote.current = ms
    const res = await api('/api/watch/position', { itemId: item.id, positionMs: ms, ended })
    if (res?.finished) setSeen(true)
  }

  useEffect(() => {
    const t = setInterval(() => { if (!video.current?.paused) savePosition() }, 15000)
    return () => {
      clearInterval(t)
      // The last write, on the way out. `at` is captured by this closure at teardown,
      // which is the number the viewer actually stopped on.
      const ms = Math.round(at * 1000)
      if (ms > 0) api('/api/watch/position', { itemId: item.id, positionMs: ms })
    }
  }, [item.id, at])

  const markWatched = async (on) => {
    setSeen(on)
    await api('/api/watch/watched', { itemId: item.id, watched: on })
    onWatchChange()
  }

  // THE HOST'S ANSWER WINS OVER THE QUEUE. The queue is whatever list this film
  // was opened from, so on the last episode of a season it ends - while the host
  // walks the whole show and hands back the first of the next one, which is what
  // "next" means to a person. The queue stays as the fallback for the moment
  // before the host answers, and for a list of films.
  const idx = queue.findIndex(q => q.id === item.id)
  const next = sib?.next || (idx >= 0 && idx + 1 < queue.length ? queue[idx + 1] : null)
  const prev = sib?.prev || (idx > 0 ? queue[idx - 1] : null)

  // THE COUNTDOWN, one second at a time, and it exists only while `left` is a
  // number - cancelling and autoplay-off are both "no number" rather than a
  // second flag to keep in step.
  useEffect(() => {
    if (left === null) return
    if (left <= 0) { if (next) { autoStart.current = true; onPlay(next) } return }
    const t = setTimeout(() => setLeft(l => (l === null ? null : l - 1)), 1000)
    return () => clearTimeout(t)
  }, [left, next?.id])

  const m = item.media || {}
  const heading = item.type === 'episode'
    ? [item.seriesTitle, episodeCode(item)].filter(Boolean).join(' · ')
    : (item.year ? String(item.year) : '')

  // EXTERNAL FIRST, and that ordering is a measurement rather than a preference: the
  // real Movies collection carries 232 embedded PGS tracks against 383 `.srt` files
  // on disk. Lead with the embedded one and most films look like they have subtitles
  // that do not work.
  const playableSubs = subs.filter(s => s.playable).sort((a, b) => (b.external ? 1 : 0) - (a.external ? 1 : 0))
  const unplayableSubs = subs.filter(s => !s.playable)

  // PREVIOUS AND NEXT ARE A TELEVISION IDEA. On an episode they are the obvious two
  // controls; on a FILM the queue is whatever list you happened to open it from, so
  // "next" means the next film alphabetically - which is not a thing anybody wants
  // offered (Tim, 2026-08-13). Hidden on films rather than disabled: a control that is
  // permanently greyed out is still a control to read past.
  const episodic = item.type === 'episode'

  return (
    <div class='playerwrap'>
      {/* CLIMBING BACK OUT, one level at a time. A film has one place to go and a
          single "back to the library" says it; an EPISODE is four levels down, and
          offering only the way to the very top means anybody wanting the rest of the
          season has to walk back in from Shows. */}
      <div class='crumbs'>
        <button onClick={onClose}>{episodic ? 'Shows' : 'Library'}</button>
        {episodic && onUp && (
          <>
            <span>/</span>
            <button onClick={() => onUp('series')}>{item.seriesTitle || 'Show'}</button>
            <span>/</span>
            <button onClick={() => onUp('season')}>
              {item.seasonNumber === 0
                ? 'Specials'
                : item.seasonNumber === null || item.seasonNumber === undefined
                  ? 'Season'
                  : 'Season ' + item.seasonNumber}
            </button>
          </>
        )}
        <span>/</span>
        <span style='color:var(--fg)'>{episodeCode(item) || item.title}</span>
      </div>

      <div class='stagewrap'>
        <div class='stage'>
          {blocked
            ? (
              <div class='refusal'>
                <div style='color:var(--danger)'><Blocked size={34} /></div>
                <h3>This one cannot be played here</h3>
                <p>{verdict.reason}</p>
                <button class='ghost' onClick={() => { setFailed(null); setForced(true) }}>Try anyway</button>
              </div>
              )
            : !dlKnown
                ? <div class='refusal' aria-hidden='true' />
                : (
              <video
                ref={video}
                key={src}
                playsinline
                onClick={() => { const v = video.current; if (v) v.paused ? v.play().catch(() => {}) : v.pause() }}
                onLoadedMetadata={e => {
                  const d = e.currentTarget.duration
                  setElDuration(Number.isFinite(d) && d > 0 ? d : 0)
                  // Only ever resumes something the viewer already started - see
                  // wantPlay. A first open stays paused. And never while the
                  // resume card is up: an episode carried in by the countdown
                  // that turns out to be half-watched must not play from zero
                  // underneath the question about where to start.
                  if (wantPlay.current && offer === null) e.currentTarget.play().catch(() => {})
                }}
                onPlay={() => { wantPlay.current = true }}
                src={src}
                onTimeUpdate={e => setAt(offset + e.currentTarget.currentTime)}
                onPause={() => savePosition()}
                onEnded={() => {
                  savePosition(true)
                  // A GENERATED STREAM CAN END WITHOUT THE FILM ENDING - the
                  // host's ffmpeg stopping is an `ended` to the element, and
                  // offering the next episode forty minutes in would be worse
                  // than saying nothing. So the card needs the clock to agree
                  // that this really was the end.
                  const reallyEnded = !duration || at >= duration * 0.9
                  if (item.type === 'episode' && next && reallyEnded) {
                    setUpNext(true)
                    setLeft(autoplay ? NEXT_SECONDS : null)
                  }
                }}
                onPlaying={() => setBusy(false)}
                onError={() => {
                  setBusy(false)
                  setFailed(generated
                    ? (verdict.status === 'convert' || burnSub
                        ? 'Converting stopped. The film itself is fine. This is the host or the connection rather than the file.'
                        : 'Repackaging stopped. The film itself is fine. This is the host or the connection rather than the file.')
                    : 'The browser stopped without saying why. That is almost always the container or the codec, and the file will play on a phone.')
                }}
              >
                {playableSubs.map(s => (
                  <track
                    key={s.id}
                    kind='subtitles'
                    label={s.title || s.language || 'Subtitles'}
                    srclang={s.language || undefined}
                    src={withBase('/api/subtitle?itemId=' + encodeURIComponent(item.id) + '&subtitleId=' + encodeURIComponent(s.id))}
                  />
                ))}
              </video>
              )}

        {/* PICK UP WHERE YOU LEFT OFF, over the picture rather than in a strip under
            it. A banner below the player was a notice about the film; this is a
            question ABOUT to watching it, and it belongs where the eye already is
            (Tim, 2026-08-13).
            The time is exact - "12:34", not "12m". Somebody deciding whether to
            resume is looking for the moment they stopped, and a rounded number does
            not tell them which of two attempts this was. */}
        {offer !== null && !blocked && (
          <div class='resumeover'>
            <div class='card'>
              <h3>Resume at {fmtClock(offer)}?</h3>
              <div class='row two'>
                <button onClick={() => {
                  wantPlay.current = true
                  seekTo(offer)
                  setOffer(null)
                  if (!generated) video.current?.play().catch(() => {})
                }}>Resume</button>
                <button class='ghost' onClick={() => {
                  // START OVER MEANS FROM ZERO, and it used to mean only "stop asking"
                  // - which left the element wherever it happened to be. On a file that
                  // is the start, so it looked right; on a repackaged stream it is not.
                  wantPlay.current = true
                  seekTo(0)
                  setOffer(null)
                  if (!generated) video.current?.play().catch(() => {})
                }}>Start Over</button>
              </div>
            </div>
          </div>
        )}

        {/* PLAYING NEXT (Tim, 2026-08-19, naming Plex's). The episode is over and
            the question is whether to carry on, so the card answers it with the
            next one's name, its length and what it is about - not with a bare
            "Next episode" button that asks somebody to remember what follows
            what.
            THE COUNTDOWN IS THE ONLY THING THAT ACTS ON ITS OWN, and it is
            visible the whole time it runs. Cancel stops it and leaves the
            finished episode on screen, paused, with the controls - nothing
            closes, nothing jumps. */}
        {upNext && next && (
          <div class='nextover'>
            <div class='nextcard'>
              <div class='nextside'>
                <button
                  class='nextdial'
                  onClick={() => { autoStart.current = true; onPlay(next) }}
                  title='Play it now'
                  aria-label={'Play ' + (next.title || 'the next episode') + ' now'}
                >
                  <svg viewBox='0 0 64 64' aria-hidden='true'>
                    <circle class='dialtrack' cx='32' cy='32' r='28' />
                    {left !== null && (
                      <circle
                        class='dialfill'
                        cx='32' cy='32' r='28'
                        style={`stroke-dasharray:${DIAL};stroke-dashoffset:${DIAL * (1 - Math.max(0, left) / NEXT_SECONDS)}`}
                      />
                    )}
                  </svg>
                  <span>{left === null ? '▶' : Math.max(0, left)}</span>
                </button>

                {/* The preference lives on the card because that is the one
                    moment anybody has an opinion about it. */}
                <label class='autoplay'>
                  <input
                    type='checkbox'
                    checked={autoplay}
                    onChange={e => {
                      const on = e.currentTarget.checked
                      setAutoplay(on)
                      writeAutoplay(on)
                      setLeft(on ? NEXT_SECONDS : null)
                    }}
                  />
                  <span>Autoplay</span>
                </label>

                <button class='ghost' onClick={() => { setLeft(null); setUpNext(false) }}>Cancel</button>
              </div>

              <div class='nextmeta'>
                <p class='eyebrow'>Playing next</p>
                <h3>{next.seriesTitle || next.title}</h3>
                <p class='nextline'>
                  {[episodeCode(next), next.title].filter(Boolean).join(' - ')}
                </p>
                <p class='hint'>
                  {[next.runtime ? fmtRuntime(next.runtime) : null, (watch?.watched || []).includes(next.id) ? 'Watched' : 'Not watched yet']
                    .filter(Boolean).join(' · ')}
                </p>
                {next.overview && <p class='nextsum'>{next.overview}</p>}
              </div>

              {next.artId && (
                <img class='nextart' src={withBase('/api/art?id=' + encodeURIComponent(next.artId))} alt='' />
              )}
            </div>
          </div>
        )}

        </div>

        {!blocked && (
          <Controls
            video={video}
            at={at}
            duration={duration}
            onSeek={seekTo}
            busy={busy}
            live={generated}
            subs={playableSubs}
          />
        )}
      </div>

      {failed && <div class='banner bad' style='margin-top:.7rem'>{failed}</div>}
      {!blocked && !remuxing && verdict.status === 'nosound' && (
        <div class='banner warn' style='margin-top:.7rem'>{verdict.reason}</div>
      )}
      {!blocked && !remuxing && verdict.status === 'unknown' && (
        <div class='banner' style='margin-top:.7rem'>{verdict.reason}</div>
      )}

      {/* WHAT IT IS AND WHAT IT IS ABOUT, and nothing else on the page (Tim,
          2026-08-13). The file's technical facts used to sit in a permanent right-hand
          column, which made the picture smaller on every screen to keep room for
          something most people never read - and read as a file inspector that happens
          to play video. They are one button away now, and cover nothing until asked. */}
      <div class='titlebar'>
        <div class='grow'>
          <h2>{item.title}</h2>
          {heading && <p class='hint' style='margin:0'>{heading}</p>}
        </div>

        {/* FOUR CONTROLS OF ONE WIDTH. Previous and Next only exist on television; the
            other two are icons so that all of them come out the same size rather than
            a row of mixed-width buttons. */}
        <div class='acts'>
          {episodic && (
            <>
              <button class='ghost' disabled={!prev} onClick={() => prev && onPlay(prev)}>Previous</button>
              <button class='ghost' disabled={!next} onClick={() => next && onPlay(next)}>Next</button>
            </>
          )}
          {/* AN ICON WITH A STATE HAS TO BE UNMISTAKABLE, or a tick means both "done"
              and "mark done". Filled while watched, outline while not, and the label
              says which way pressing it goes. */}
          <button
            class={'icon' + (seen ? ' on' : '')}
            title={seen ? 'Watched. Press to unmark' : 'Mark as watched'}
            aria-label={seen ? 'Mark as unwatched' : 'Mark as watched'}
            aria-pressed={seen}
            onClick={() => markWatched(!seen)}
          ><Check size={17} /></button>
          <button
            class={'icon' + (details ? ' on' : '')}
            title='Details'
            aria-label='Details'
            aria-expanded={details}
            onClick={() => setDetails(!details)}
          ><Info size={17} /></button>
        </div>
      </div>

      {item.overview && <p class='overview'>{item.overview}</p>}

      {/* The sheet, and the scrim that closes it. Over the page rather than beside it,
          so nothing is narrower for its sake while it is shut. */}
      <div class={'scrim' + (details ? ' on' : '')} onClick={() => setDetails(false)} />
      <aside class={'sheet' + (details ? ' open' : '')} aria-hidden={!details}>
        <div class='sheet-head'>
          <h3>Details</h3>
          <button class='iconbtn' onClick={() => setDetails(false)} aria-label='Close'><Close size={16} /></button>
        </div>

        <dl class='meta'>
          {item.runtime ? <><dt>Length</dt><dd>{fmtExact(item.runtime)}</dd></> : null}
          <dt>File</dt>
          <dd>
            {[containerName(m.container), m.videoCodec && m.videoCodec.toUpperCase(), m.audioCodec && m.audioCodec.toUpperCase()]
              .filter(Boolean).join(' · ') || 'not reported'}
            {m.size ? <span class='hint'> · {fmtSize(m.size)}</span> : null}
          </dd>
          {/* IN WORDS, NOT PILLS. A coloured badge reads as a status somebody is
              meant to act on; this is an explanation, and the only reason it earns a
              place at all is that it answers a real question - why jumping takes a
              moment on some films and not others (Tim, 2026-08-13). */}
          <dt>How it is playing</dt>
          <dd>
            {blocked && 'Your browser will not open this one at all.'}
            {!blocked && remuxing && (
              <>
                {verdict.status === 'convert'
                  ? `Your browser cannot decode ${String(m.videoCodec || '').toUpperCase()} video, so the host converts the picture to H.264 on its own video hardware as it streams.`
                  : verdict.status === 'nosound'
                    ? 'Your browser cannot decode this soundtrack, so it is rebuilt as it streams. The picture is untouched.'
                    : `Your browser will not open a ${containerName(m.container)} file, so the picture and sound are put, untouched, in one it will as they stream.`}
                {' '}Nothing is written to disk, which is why jumping to a new point takes a moment.
              </>
            )}
            {!blocked && !remuxing && verdict.status === 'play' && 'Straight from the file, exactly as it is on the disk.'}
            {!blocked && !remuxing && verdict.status === 'unknown' && 'Your browser has not said whether it can open this one.'}
          </dd>
        </dl>

        {/* KEEP A COPY HERE (desktop-client phase 2), remote libraries only -
            downloading your own files to the machine they are on is a copy for
            nothing. The friend's box decides converted-or-raw exactly as it
            decides playback; once kept, the film plays off this disk even with
            their server switched off. */}
        {remote && (
          <>
            <h3 style='margin-top:1rem'>On this computer</h3>
            {/* ICON BUTTONS AND A REAL BAR (Tim, 2026-08-17): the hint carries
                the words, the button carries one clear symbol, and progress is
                a bar rather than a number to squint at. */}
            {!dl && (
              <div class='dlrow'>
                <p class='hint'>
                  Keep a copy on this machine. It plays here even when their
                  server is off.
                </p>
                <button
                  class='ghost iconbtn'
                  title='Download to this computer'
                  aria-label='Download to this computer'
                  onClick={async () => {
                    setDlErr('')
                    const r = await api('/api/download', { itemId: item.id, capabilities: caps })
                    if (r?.error) return setDlErr(r.error)
                    setDlTick(t => t + 1)
                  }}
                ><DownloadIcon size={18} /></button>
              </div>
            )}
            {dl?.downloading && (
              <>
                <div class='dlrow'>
                  <span class='meter dlmeter'>
                    <i style={`width:${dl.size ? Math.min(99, Math.round((dl.got / dl.size) * 100)) : 0}%`} />
                  </span>
                  <span class='hint'>{dl.size ? Math.min(99, Math.round((dl.got / dl.size) * 100)) : 0}%</span>
                  <button
                    class='ghost iconbtn'
                    title='Cancel the download'
                    aria-label='Cancel the download'
                    onClick={async () => { await api('/api/downloads/cancel', { itemId: item.id }); setDlTick(t => t + 1) }}
                  ><Close size={16} /></button>
                </div>
                {dl.converting && <p class='hint'>Their box is converting it as it sends.</p>}
              </>
            )}
            {kept && (
              <div class='dlrow'>
                <p class='hint'>
                  Downloaded{kept.converted ? ', as converted by their machine' : ''}. It
                  plays from this computer now, even with their server off.
                </p>
                <button
                  class='ghost iconbtn'
                  title='Remove the copy'
                  aria-label='Remove the copy'
                  onClick={async () => { await api('/api/downloads/remove', { itemId: item.id }); setDlTick(t => t + 1) }}
                ><Trash size={17} /></button>
              </div>
            )}
            {dlErr && <p class='error'>{dlErr}</p>}
          </>
        )}

        {(playableSubs.length > 0 || unplayableSubs.length > 0) && (
          <>
            {/* NO BADGE ON THE ONES THAT WORK. This list IS the list of subtitles you
                can turn on - saying "on the player" beside each is a label for the
                obvious, in a colour that suggests something happened. What earns its
                place is the opposite: the ones you cannot have, and why. */}
            <h3 style='margin-top:1rem'>Subtitles</h3>
            <div class='tracklist'>
              {playableSubs.map(s => (
                <div class='sub' key={s.id}>
                  <span>{s.title || s.language || 'Subtitles'}</span>
                  <span class='hint'>{s.external ? 'file on the disk' : 'in the film'}</span>
                </div>
              ))}
              {unplayableSubs.map(s => (
                // An image track the host can press into the picture instead:
                // the refusal becomes a button. Choosing one restarts the
                // stream as a conversion at the current position; turning it
                // off restarts clean, because burned frames cannot be
                // un-burned in place. The same feature the phone shipped.
                s.burnable ? (
                  <div class='sub' key={s.id}>
                    <span>{s.title || s.language || 'Subtitles'}</span>
                    {burnSub === s.id ? (
                      <button class='ghost' onClick={() => { setBurnSub(null); setOffset(at); setBusy(true) }}>
                        pressed into the picture - turn off
                      </button>
                    ) : (
                      <button class='ghost' onClick={() => { setBurnSub(s.id); setOffset(at); setBusy(true) }}>
                        press into the picture
                      </button>
                    )}
                  </div>
                ) : (
                  <div class='sub off' key={s.id} title={s.reason || ''}>
                    <span>{s.title || s.language || 'Subtitles'}</span>
                    <span class='hint'>not available</span>
                  </div>
                )
              ))}
            </div>
            {playableSubs.length > 0 && (
              <p class='hint'>Turn one on with the subtitles button in the player.</p>
            )}
            {unplayableSubs.some(s => s.burnable) ? (
              <p class='hint'>
                These subtitles are pictures, so your box presses them into the film
                itself - choosing one restarts the stream where you are.
              </p>
            ) : (
              unplayableSubs.length > 0 && <p class='hint'>{unplayableSubs[0].reason}</p>
            )}
          </>
        )}
      </aside>
    </div>
  )
}
