// The player.
//
// TWO WAYS TO GET A FILM, and the browser never chooses between them:
//
//   /api/stream  - the actual file, byte-ranged. Free, exact, and seekable by the
//                  native scrubber. Used whenever the browser will open the file.
//   /api/remux   - repackaged into MP4 on the fly, and the soundtrack rebuilt if the
//                  browser cannot decode it. Used when the browser refuses the
//                  container or the audio - never for the picture, which is never
//                  re-encoded.
//
// The HOST decides which. A client can describe itself and cannot demand to be
// repackaged, because direct play is free and exact and remux is neither.
//
// WHY THE SCRUBBER IS OURS ON A REPACKAGED FILM. Generated bytes have no stable byte
// offsets - there is no "byte 2.4 billion" until everything before it has been made -
// so a native <video> seek, which IS a byte-range request, cannot work. Instead the
// player asks the host to start again at a new time and adds that offset to the
// element's own clock. The cost is a moment's rebuffer on each seek. The alternative
// was a byte-to-time map faked from average bitrate, which is approximate on constant
// bitrate video and simply wrong on variable, which is most video.
//
// NOTHING FAILS SILENTLY. A file that cannot be played even repackaged says which
// part is the problem, and "Try anyway" is always offered, because canPlayType
// answers about a codec family rather than a file and can be wrong in both
// directions.

import { useState, useEffect, useRef } from 'preact/hooks'
import { api, fmtRuntime, fmtSize, fmtClock, episodeCode } from './api'
import { verdictFor, containerName, capabilityQuery } from './playback'

export default function Player ({ item, caps, queue = [], onPlay, onClose }) {
  const [forced, setForced] = useState(false)
  const [subs, setSubs] = useState([])
  const [failed, setFailed] = useState(null)
  const [at, setAt] = useState(0)
  // Where the CURRENT repackaged stream begins. The element's own currentTime counts
  // from zero on every restart, so the clock the viewer sees is this plus that.
  const [offset, setOffset] = useState(0)
  const [busy, setBusy] = useState(false)
  const video = useRef(null)

  const verdict = verdictFor(item, caps)
  // The browser can see the common case without a round trip: the container is
  // refused and the streams inside it are ones it can decode. The host still makes
  // the real decision and will answer 409 if it disagrees.
  // Repackage when it is the only way to play it AND when it is the only way to HEAR
  // it. A silent film is broken, and rebuilding a soundtrack is cheap - so a
  // 'nosound' verdict is fixed rather than merely reported.
  const remuxing = ((verdict.status === 'refuse' || verdict.status === 'nosound') && verdict.remuxable) || forced
  const blocked = verdict.status === 'refuse' && !verdict.remuxable && !forced

  // SECONDS ALREADY. This used to multiply by 60, on the same misreading that showed
  // 300 as a 116-hour film - and it was worse here than in a label: the scrubber's
  // range was sixty times too long, so dragging it anywhere past the very start asked
  // the host to begin at a time beyond the end of the film. ffmpeg produced nothing,
  // the browser stalled, and playback stopped and would not resume. That is the
  // "sometimes pauses and will not start again" Tim reported.
  const duration = item.runtime || 0

  useEffect(() => {
    setForced(false); setFailed(null); setAt(0); setOffset(0); setSubs([]); setBusy(false)
    let live = true
    api('/api/subtitles?itemId=' + encodeURIComponent(item.id)).then(res => {
      if (live) setSubs(res.items || [])
    })
    return () => { live = false }
  }, [item.id])

  const src = remuxing
    ? '/api/remux?id=' + encodeURIComponent(item.id) + '&t=' + Math.floor(offset) + '&' + capabilityQuery(caps)
    : '/api/stream?id=' + encodeURIComponent(item.id)

  // Seeking a repackaged film is asking the host to start again from there.
  const seekTo = (seconds) => {
    const t = Math.max(0, duration ? Math.min(seconds, duration - 2) : seconds)
    setBusy(true); setOffset(t); setAt(t); setFailed(null)
  }

  const idx = queue.findIndex(q => q.id === item.id)
  const next = idx >= 0 && idx + 1 < queue.length ? queue[idx + 1] : null
  const prev = idx > 0 ? queue[idx - 1] : null

  const m = item.media || {}
  const heading = item.type === 'episode'
    ? [item.seriesTitle, episodeCode(item)].filter(Boolean).join(' · ')
    : (item.year ? String(item.year) : '')

  // EXTERNAL FIRST, and that ordering is a measurement rather than a preference: the
  // real Movies collection carries 232 embedded PGS tracks against 383 `.srt` files
  // on disk. Lead with the embedded one and most films look like they have subtitles
  // that do not work.
  const playableSubs = subs.filter(s => s.playable).sort((a, b) => (b.external ? 1 : 0) - (a.external ? 1 : 0))
  const unplayableSubs = subs.filter(s => !s.playable)

  return (
    <div class='playerwrap'>
      <div>
        <div class='stage'>
          {blocked
            ? (
              <div class='refusal'>
                <div style='font-size:2rem'>🚫</div>
                <h3>This one cannot be played here</h3>
                <p>{verdict.reason}</p>
                <button class='ghost' onClick={() => { setFailed(null); setForced(true) }}>Try anyway</button>
              </div>
              )
            : (
              <video
                ref={video}
                key={src}
                controls
                autoplay
                playsinline
                src={src}
                onTimeUpdate={e => setAt(offset + e.currentTarget.currentTime)}
                onPlaying={() => setBusy(false)}
                // THE NATIVE SCRUBBER AND OURS WERE FIGHTING EACH OTHER.
                //
                // A repackaged stream arrives as it is made, so the element only knows
                // about the seconds it has actually received: its own clock keeps
                // resetting as fragments land, and dragging its bar past the buffered
                // edge asks for bytes that do not exist yet. The browser then stalls,
                // and playback stops and does not resume.
                //
                // So a native seek is honoured when it lands inside what the element
                // already holds - that is genuinely instant and worth keeping - and
                // otherwise it is turned into what it really means: start the film
                // again from there.
                onSeeking={e => {
                  if (!remuxing) return
                  const el = e.currentTarget
                  const want = el.currentTime
                  for (let i = 0; i < el.buffered.length; i++) {
                    if (want >= el.buffered.start(i) && want <= el.buffered.end(i)) return
                  }
                  seekTo(offset + want)
                }}
                onError={() => {
                  setBusy(false)
                  setFailed(remuxing
                    ? 'Repackaging stopped. The film itself is fine - this is the host or the connection rather than the file.'
                    : 'The browser stopped without saying why. That is almost always the container or the codec, and the file will play on a phone.')
                }}
              >
                {playableSubs.map(s => (
                  <track
                    key={s.id}
                    kind='subtitles'
                    label={s.title || s.language || 'Subtitles'}
                    srclang={s.language || undefined}
                    src={'/api/subtitle?itemId=' + encodeURIComponent(item.id) + '&subtitleId=' + encodeURIComponent(s.id)}
                  />
                ))}
              </video>
              )}
        </div>

        {/* A repackaged film cannot use the element's own scrubber, so it gets one
            that works the only way generated bytes allow: by restarting. */}
        {/* THE ONE TO TRUST while a film is being repackaged. The player's own bar
            only knows the seconds it has received so far, so it keeps resetting; this
            one is the whole film. Shown only when repackaging, because a file playing
            straight from disk has a native scrubber that works perfectly. */}
        {remuxing && !blocked && duration > 0 && (
          <div style='margin-top:.6rem'>
            <div class='row' style='gap:.5rem'>
              <span class='hint mono'>{fmtClock(at)}</span>
              <input
                type='range' min='0' max={Math.floor(duration)} value={Math.floor(at)}
                style='flex:1'
                onChange={e => seekTo(Number(e.currentTarget.value))}
              />
              <span class='hint mono'>{fmtClock(duration)}</span>
            </div>
            <p class='hint' style='margin-top:.2rem'>
              Use this bar to jump around. The player's own timeline counts only the part
              it has been sent so far, so it restarts as the film streams.
            </p>
          </div>
        )}

        {busy && <div class='banner' style='margin-top:.7rem'>Starting from {fmtClock(offset)}…</div>}
        {failed && <div class='banner bad' style='margin-top:.7rem'>{failed}</div>}

        {!blocked && remuxing && (
          <div class='banner good' style='margin-top:.7rem'>
            {verdict.status === 'nosound'
              ? <><b>Sound rebuilt for your browser.</b> {verdict.reason} Nothing was written to disk.</>
              : <><b>Repackaged for your browser.</b> Your browser will not open a {containerName(m.container)}
                  file. The picture and sound are untouched - only the wrapper around them
                  changed, on the fly, and nothing was written to disk.</>}
          </div>
        )}
        {!blocked && !remuxing && verdict.status === 'nosound' && (
          <div class='banner warn' style='margin-top:.7rem'>{verdict.reason}</div>
        )}
        {!blocked && !remuxing && verdict.status === 'unknown' && (
          <div class='banner' style='margin-top:.7rem'>{verdict.reason}</div>
        )}

        <div class='row' style='margin-top:.8rem'>
          <button class='ghost' disabled={!prev} onClick={() => prev && onPlay(prev)}>Previous</button>
          <button class='ghost' disabled={!next} onClick={() => next && onPlay(next)}>Next episode</button>
          <div class='spacer' />
          {!blocked && !remuxing && <span class='hint'>{fmtClock(at)}</span>}
          <button class='ghost' onClick={onClose}>Back to the library</button>
        </div>
      </div>

      <div>
        <h2>{item.title}</h2>
        {heading && <p class='hint' style='margin-top:0'>{heading}</p>}

        {item.overview && <p style='font-size:.9rem'>{item.overview}</p>}

        <dl class='meta'>
          {item.runtime ? <><dt>Length</dt><dd>{fmtRuntime(item.runtime)}</dd></> : null}
          <dt>File</dt>
          <dd>
            {[containerName(m.container), m.videoCodec && m.videoCodec.toUpperCase(), m.audioCodec && m.audioCodec.toUpperCase()]
              .filter(Boolean).join(' · ') || 'not reported'}
            {m.size ? <span class='hint'> · {fmtSize(m.size)}</span> : null}
          </dd>
          <dt>How it is playing</dt>
          <dd>
            {blocked && <span class='chip bad'>will not open</span>}
            {!blocked && remuxing && <span class='chip accent'>repackaged</span>}
            {!blocked && !remuxing && verdict.status === 'play' && <span class='chip good'>straight from the file</span>}
            {!blocked && !remuxing && verdict.status === 'nosound' && <span class='chip warn'>picture only</span>}
            {!blocked && !remuxing && verdict.status === 'unknown' && <span class='chip'>unknown</span>}
          </dd>
        </dl>

        {(playableSubs.length > 0 || unplayableSubs.length > 0) && (
          <>
            <h3>Subtitles</h3>
            <div class='tracklist'>
              {playableSubs.map(s => (
                <div class='sub' key={s.id}>
                  <span>{s.title || s.language || 'Subtitles'}{s.external ? ' (file)' : ''}</span>
                  <span class='chip good'>on the player</span>
                </div>
              ))}
              {unplayableSubs.map(s => (
                <div class='sub off' key={s.id} title={s.reason || ''}>
                  <span>{s.title || s.language || 'Subtitles'}</span>
                  <span class='chip bad'>not available</span>
                </div>
              ))}
            </div>
            {unplayableSubs.length > 0 && <p class='hint'>{unplayableSubs[0].reason}</p>}
          </>
        )}
      </div>
    </div>
  )
}
