// The player.
//
// TWO WAYS TO GET A FILM, and the browser never chooses between them:
//
//   /api/stream  - the actual file, byte-ranged. Free, exact, and seekable by the
//                  native scrubber. Used whenever the browser will open the file.
//   /api/remux   - repackaged into MP4 on the fly, and the soundtrack rebuilt if the
//                  browser cannot decode it. Used when the browser refuses the
//                  container or the audio - never for the picture, which is never
//                  re-encoded.
//
// The HOST decides which. A client can describe itself and cannot demand to be
// repackaged, because direct play is free and exact and remux is neither.
//
// WHY THE SCRUBBER IS OURS ON A REPACKAGED FILM. Generated bytes have no stable byte
// offsets - there is no "byte 2.4 billion" until everything before it has been made -
// so a native <video> seek, which IS a byte-range request, cannot work. Instead the
// player asks the host to start again at a new time and adds that offset to the
// element's own clock. The cost is a moment's rebuffer on each seek. The alternative
// was a byte-to-time map faked from average bitrate, which is approximate on constant
// bitrate video and simply wrong on variable, which is most video.
//
// NOTHING FAILS SILENTLY. A file that cannot be played even repackaged says which
// part is the problem, and "Try anyway" is always offered, because canPlayType
// answers about a codec family rather than a file and can be wrong in both
// directions.

import { useState, useEffect, useRef } from 'preact/hooks'
import { api, fmtRuntime, fmtSize, episodeCode } from './api'
import { verdictFor, containerName, capabilityQuery } from './playback'
import Controls from './Controls'
import { Blocked, Check } from './icons'

export default function Player ({ item, caps, queue = [], onPlay, onClose, onUp = null, watch = null, onWatchChange = () => {} }) {
  const [forced, setForced] = useState(false)
  const [subs, setSubs] = useState([])
  const [failed, setFailed] = useState(null)
  const [at, setAt] = useState(0)
  // Where the CURRENT repackaged stream begins. The element's own currentTime counts
  // from zero on every restart, so the clock the viewer sees is this plus that.
  const [offset, setOffset] = useState(0)
  const [busy, setBusy] = useState(false)
  // Non-null while the "you got to 42 minutes" card is up. NOTHING JUMPS ON ITS OWN:
  // somebody who opened a film to watch the beginning again should not have to scrub
  // backwards out of a resume they never asked for.
  const [offer, setOffer] = useState(null)
  const [seen, setSeen] = useState(false)
  const video = useRef(null)
  // The last position WRITTEN, so the fifteen-second heartbeat can skip a write when
  // nothing has moved - a paused film should not keep writing the same number.
  const wrote = useRef(0)

  const verdict = verdictFor(item, caps)
  // The browser can see the common case without a round trip: the container is
  // refused and the streams inside it are ones it can decode. The host still makes
  // the real decision and will answer 409 if it disagrees.
  // Repackage when it is the only way to play it AND when it is the only way to HEAR
  // it. A silent film is broken, and rebuilding a soundtrack is cheap - so a
  // 'nosound' verdict is fixed rather than merely reported.
  const remuxing = ((verdict.status === 'refuse' || verdict.status === 'nosound') && verdict.remuxable) || forced
  const blocked = verdict.status === 'refuse' && !verdict.remuxable && !forced

  // SECONDS ALREADY. This used to multiply by 60, on the same misreading that showed
  // 300 as a 116-hour film - and it was worse here than in a label: the scrubber's
  // range was sixty times too long, so dragging it anywhere past the very start asked
  // the host to begin at a time beyond the end of the film. ffmpeg produced nothing,
  // the browser stalled, and playback stopped and would not resume. That is the
  // "sometimes pauses and will not start again" Tim reported.
  // SECONDS ALREADY - this used to multiply by 60, the same misreading that showed
  // 300 as a 116-hour film, and here it made the scrub bar's range sixty times too
  // long so every jump landed past the end of the film.
  //
  // `elDuration` is preferred when the element knows one, because for a file playing
  // straight from disk it is exact. A repackaged stream cannot report one at all -
  // its bytes are still being made - so there the library's own runtime is all there
  // is, and it is why the item model carrying a runtime matters more than it looks.
  const [elDuration, setElDuration] = useState(0)
  const duration = (!remuxing && elDuration > 0 ? elDuration : item.runtime) || 0

  useEffect(() => {
    setForced(false); setFailed(null); setAt(0); setOffset(0); setSubs([]); setBusy(false)
    setOffer(null)
    wrote.current = 0
    let live = true
    api('/api/subtitles?itemId=' + encodeURIComponent(item.id)).then(res => {
      if (live) setSubs(res.items || [])
    })

    // Where this person got to, from the shelf we already have rather than a second
    // round trip. `watch` is a snapshot from when the library last read it, which is
    // exactly right: it is what was true when they clicked.
    const prior = (watch?.continue || []).find(x => x.id === item.id)
    if (prior?.resume?.positionMs > 0) setOffer(prior.resume.positionMs / 1000)
    setSeen((watch?.watched || []).includes(item.id))

    return () => { live = false }
  }, [item.id])

  const src = remuxing
    ? '/api/remux?id=' + encodeURIComponent(item.id) + '&t=' + Math.floor(offset) + '&' + capabilityQuery(caps)
    : '/api/stream?id=' + encodeURIComponent(item.id)

  // ONE SEEK, and the controls above it cannot tell the difference.
  //
  // Playing from the file, the browser holds the whole thing and a seek is instant.
  // Repackaged, the bytes past this point do not exist yet, so a seek means asking
  // the host to start again from there - which costs a second and is the only thing
  // generated bytes allow.
  const seekTo = (seconds) => {
    const t = Math.max(0, duration ? Math.min(seconds, duration - 1) : seconds)
    setFailed(null)

    if (!remuxing && video.current) {
      video.current.currentTime = t
      setAt(t)
      return
    }

    setBusy(true); setOffset(t); setAt(t)
  }

  // TELL THE HOST WHERE WE ARE. Every fifteen seconds, on pause, and on the way out -
  // never on `timeupdate`, which fires four times a second and would be 28,800 writes
  // across a two-hour film.
  //
  // The host decides what the number MEANS: whether it counts as started, whether it
  // counts as finished, and what to do with a position past the end of a file that has
  // been re-encoded since. None of that is decided here, because the phone will need
  // the same answers and two copies of the rule is one copy that drifts.
  const savePosition = async (ended = false) => {
    const ms = Math.round(at * 1000)
    if (!ended && Math.abs(ms - wrote.current) < 5000) return
    wrote.current = ms
    const res = await api('/api/watch/position', { itemId: item.id, positionMs: ms, ended })
    if (res?.finished) setSeen(true)
  }

  useEffect(() => {
    const t = setInterval(() => { if (!video.current?.paused) savePosition() }, 15000)
    return () => {
      clearInterval(t)
      // The last write, on the way out. `at` is captured by this closure at teardown,
      // which is the number the viewer actually stopped on.
      const ms = Math.round(at * 1000)
      if (ms > 0) api('/api/watch/position', { itemId: item.id, positionMs: ms })
    }
  }, [item.id, at])

  const markWatched = async (on) => {
    setSeen(on)
    await api('/api/watch/watched', { itemId: item.id, watched: on })
    onWatchChange()
  }

  const idx = queue.findIndex(q => q.id === item.id)
  const next = idx >= 0 && idx + 1 < queue.length ? queue[idx + 1] : null
  const prev = idx > 0 ? queue[idx - 1] : null

  const m = item.media || {}
  const heading = item.type === 'episode'
    ? [item.seriesTitle, episodeCode(item)].filter(Boolean).join(' · ')
    : (item.year ? String(item.year) : '')

  // EXTERNAL FIRST, and that ordering is a measurement rather than a preference: the
  // real Movies collection carries 232 embedded PGS tracks against 383 `.srt` files
  // on disk. Lead with the embedded one and most films look like they have subtitles
  // that do not work.
  const playableSubs = subs.filter(s => s.playable).sort((a, b) => (b.external ? 1 : 0) - (a.external ? 1 : 0))
  const unplayableSubs = subs.filter(s => !s.playable)

  return (
    <div class='playerwrap'>
      <div>
        <div class='stagewrap'>
        <div class='stage'>
          {blocked
            ? (
              <div class='refusal'>
                <div style='color:var(--danger)'><Blocked size={34} /></div>
                <h3>This one cannot be played here</h3>
                <p>{verdict.reason}</p>
                <button class='ghost' onClick={() => { setFailed(null); setForced(true) }}>Try anyway</button>
              </div>
              )
            : (
              <video
                ref={video}
                key={src}
                autoplay
                playsinline
                onClick={() => { const v = video.current; if (v) v.paused ? v.play().catch(() => {}) : v.pause() }}
                onLoadedMetadata={e => {
                  const d = e.currentTarget.duration
                  setElDuration(Number.isFinite(d) && d > 0 ? d : 0)
                }}
                src={src}
                onTimeUpdate={e => setAt(offset + e.currentTarget.currentTime)}
                onPause={() => savePosition()}
                // The element reaching the end is believed whatever the clock says -
                // a file whose header lies about its duration still finished.
                onEnded={() => savePosition(true)}
                onPlaying={() => setBusy(false)}
                onError={() => {
                  setBusy(false)
                  setFailed(remuxing
                    ? 'Repackaging stopped. The film itself is fine - this is the host or the connection rather than the file.'
                    : 'The browser stopped without saying why. That is almost always the container or the codec, and the file will play on a phone.')
                }}
              >
                {playableSubs.map(s => (
                  <track
                    key={s.id}
                    kind='subtitles'
                    label={s.title || s.language || 'Subtitles'}
                    srclang={s.language || undefined}
                    src={'/api/subtitle?itemId=' + encodeURIComponent(item.id) + '&subtitleId=' + encodeURIComponent(s.id)}
                  />
                ))}
              </video>
              )}
        </div>

        {/* THE SAME CONTROLS FOR EVERY FILM. Whether the host is handing over the
            file or repackaging it as it goes is its business, not the viewer's, and
            two different sets of controls made that difference their problem. */}
        {/* PICK UP WHERE YOU LEFT OFF, offered rather than done. Somebody who opened a
            film to watch the start again should not have to scrub backwards out of a
            jump they never asked for. */}
        {offer !== null && !blocked && (
          <div class='resumeoffer'>
            <span>You stopped at <b>{fmtRuntime(Math.round(offer))}</b>.</span>
            <button onClick={() => { seekTo(offer); setOffer(null) }}>Resume</button>
            <button class='ghost' onClick={() => setOffer(null)}>Start over</button>
          </div>
        )}

        {!blocked && (
          <Controls
            video={video}
            at={at}
            duration={duration}
            onSeek={seekTo}
            busy={busy}
            live={remuxing}
            subs={playableSubs}
          />
        )}
        </div>

        {failed && <div class='banner bad' style='margin-top:.7rem'>{failed}</div>}

        {/* NO BANNER FOR A FILM THAT IS SIMPLY PLAYING. It used to announce
            "Sound rebuilt for your browser" over every repackaged film, which is a
            notice about the host's internals dressed up as news for the viewer -
            and repackaging is the normal case on this library rather than an
            exception. The quiet "repackaged" tag beside the clock is enough, and
            the detail is on the right where the rest of the file's facts are. */}
        {!blocked && !remuxing && verdict.status === 'nosound' && (
          <div class='banner warn' style='margin-top:.7rem'>{verdict.reason}</div>
        )}
        {!blocked && !remuxing && verdict.status === 'unknown' && (
          <div class='banner' style='margin-top:.7rem'>{verdict.reason}</div>
        )}

        <div class='row' style='margin-top:.8rem'>
          <button class='ghost' disabled={!prev} onClick={() => prev && onPlay(prev)}>Previous</button>
          <button class='ghost' disabled={!next} onClick={() => next && onPlay(next)}>Next episode</button>
          <div class='spacer' />
          <button class='ghost' onClick={onClose}>Back to the library</button>
        </div>
      </div>

      <div>
        {/* CLIMBING BACK OUT, one level at a time. A film has one place to go and a
            single "back to the library" says it; an EPISODE is four levels down, and
            offering only the way to the very top means anybody wanting the rest of the
            season has to walk back in from Shows (Tim, 2026-08-13).
            The crumbs are the same ones the library draws, so the two read as one
            navigation rather than two ideas about where you are. */}
        <div class='crumbs'>
          <button onClick={onClose}>{item.type === 'episode' ? 'Shows' : 'Library'}</button>
          {item.type === 'episode' && onUp && (
            <>
              <span>/</span>
              <button onClick={() => onUp('series')}>{item.seriesTitle || 'Show'}</button>
              <span>/</span>
              <button onClick={() => onUp('season')}>
                {item.seasonNumber === 0
                  ? 'Specials'
                  : item.seasonNumber === null || item.seasonNumber === undefined
                    ? 'Season'
                    : 'Season ' + item.seasonNumber}
              </button>
            </>
          )}
          <span>/</span>
          <span style='color:var(--fg)'>{episodeCode(item) || item.title}</span>
        </div>

        <h2>{item.title}</h2>
        {heading && <p class='hint' style='margin-top:0'>{heading}</p>}

        {item.overview && <p style='font-size:.9rem'>{item.overview}</p>}

        <dl class='meta'>
          {item.runtime ? <><dt>Length</dt><dd>{fmtRuntime(item.runtime)}</dd></> : null}
          <dt>File</dt>
          <dd>
            {[containerName(m.container), m.videoCodec && m.videoCodec.toUpperCase(), m.audioCodec && m.audioCodec.toUpperCase()]
              .filter(Boolean).join(' · ') || 'not reported'}
            {m.size ? <span class='hint'> · {fmtSize(m.size)}</span> : null}
          </dd>
          <dt>How it is playing</dt>
          <dd>
            {blocked && <span class='chip bad'>will not open</span>}
            {!blocked && remuxing && (
              <>
                <span class='chip accent'>repackaged</span>
                <div class='hint' style='margin-top:.3rem'>
                  {verdict.status === 'nosound'
                    ? 'Your browser cannot decode this soundtrack, so it is rebuilt as it streams. The picture is untouched.'
                    : `Your browser will not open a ${containerName(m.container)} file, so the picture and sound are put in one it will, untouched, as they stream.`}
                  {' '}Nothing is written to disk, which is why jumping to a new point takes a moment.
                </div>
              </>
            )}
            {!blocked && !remuxing && verdict.status === 'play' && <span class='chip good'>straight from the file</span>}
            {!blocked && !remuxing && verdict.status === 'unknown' && <span class='chip'>unknown</span>}
          </dd>
        </dl>

        {/* THE AUTOMATIC RULE WILL BE WRONG SOMETIMES - a film watched on another
            device, an episode somebody else put on - so correcting it is one click
            rather than a trip to a settings screen. */}
        <div class='row' style='margin:.6rem 0'>
          <button class={seen ? '' : 'ghost'} onClick={() => markWatched(!seen)}>
            {seen ? <><Check size={14} /> Watched</> : 'Mark as watched'}
          </button>
        </div>

        {(playableSubs.length > 0 || unplayableSubs.length > 0) && (
          <>
            <h3>Subtitles</h3>
            <div class='tracklist'>
              {playableSubs.map(s => (
                <div class='sub' key={s.id}>
                  <span>{s.title || s.language || 'Subtitles'}{s.external ? ' (file)' : ''}</span>
                  <span class='chip good'>on the player</span>
                </div>
              ))}
              {unplayableSubs.map(s => (
                <div class='sub off' key={s.id} title={s.reason || ''}>
                  <span>{s.title || s.language || 'Subtitles'}</span>
                  <span class='chip bad'>not available</span>
                </div>
              ))}
            </div>
            {unplayableSubs.length > 0 && <p class='hint'>{unplayableSubs[0].reason}</p>}
          </>
        )}
      </div>
    </div>
  )
}
