#!/usr/bin/env bash
# Build PearCinema for an iPhone SIMULATOR on the Mac, install it and launch it.
#
# Run from the repo root on the dev box (passwordless ssh to the Mac):
#   bash scripts/ios-sim-build.sh                  # sync, install, prebuild, build, run
#   SKIP_SYNC=1 bash scripts/ios-sim-build.sh      # reuse the tree already on the Mac
#   SKIP_INSTALL=1 bash scripts/ios-sim-build.sh   # reuse node_modules on the Mac
#   SKIP_BUILD=1 bash scripts/ios-sim-build.sh     # reuse the .app, just install and run
#
# THE SIMULATOR IS THE DEFAULT TARGET, per company rule 7: it is faster, needs no
# pairing or provisioning, and shows Release console output a device hides. What it
# CANNOT answer is anything gated on iOS Local Network permission (it inherits the
# Mac's network stack and never shows the prompt), genuine multi-peer over the LAN, or
# background execution. Those need the iPhone SE and a signed build.
#
# Assembled from peartune/scripts/ios-device-build.sh, which learned all of this the
# expensive way. Everything below exists because something failed without it.
set -euo pipefail

MAC="${MAC:-Tims-Mac-mini.local}"
# The siblings matter: @peerloom/client and @peerloom/host are `file:../` dependencies,
# so the Mac needs the same three-directories-side-by-side shape this box has or npm
# install resolves nothing.
SUITE="${SUITE:-peerloomllc}"
DEST="$SUITE/pearcinema"
# RELEASE, NOT DEBUG, and this is not a preference. An Expo Debug build loads its JS
# from a Metro dev server on localhost:8081 and shows "No bundle URL present" without
# one, which is the iOS face of company rule 5: a build that needs a tethered server is
# useless the moment nobody is tethering it. A Release build embeds the bundle.
CONFIG="${CONFIG:-Release}"
SIM_NAME="${SIM_NAME:-PearCinema-Test}"
SIM_DEVICE="${SIM_DEVICE:-iPhone 16}"
BUNDLE_ID="${BUNDLE_ID:-com.pearcinema}"
SCHEME="${SCHEME:-PearCinema}"

# Node is a HOMEBREW install and a non-interactive ssh shell does not get it on PATH,
# so every remote command that touches npm has to prepend this. LANG matters too:
# CocoaPods dies with "Unicode Normalization not appropriate for ASCII-8BIT" when the
# ssh session has no UTF-8 locale, which is the default over ssh.
REMOTE_ENV='export PATH=/opt/homebrew/bin:$PATH LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8;'
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUITE_ROOT="$(cd "$REPO_ROOT/.." && pwd)"

say () { printf '\n== %s ==\n' "$1"; }
mac () { ssh -o BatchMode=yes "$MAC" "$REMOTE_ENV $*"; }

if [ -z "${SKIP_SYNC:-}" ]; then
  say "syncing the app and its two sibling packages to $MAC:~/$SUITE/"
  # android/ is excluded because it is regenerated by prebuild and is 5 GB of build
  # output; ios/ is NOT excluded, so a Pods install survives between runs.
  for dir in pearcinema peerloom-client peerloom-host; do
    [ -d "$SUITE_ROOT/$dir" ] || { echo "missing $SUITE_ROOT/$dir - the file: dependencies will not resolve" >&2; exit 1; }
    rsync -az --delete \
      --exclude '.git' --exclude 'node_modules' --exclude 'android' \
      --exclude 'ios/build' --exclude 'ios/Pods' --exclude 'desktop/dist' \
      --exclude 'desktop/node_modules' --exclude 'host/node_modules' \
      "$SUITE_ROOT/$dir/" "$MAC:$SUITE/$dir/"
    echo "  $dir"
  done
fi

if [ -z "${SKIP_INSTALL:-}" ]; then
  say "npm install on the Mac (first run takes a few minutes)"
  mac "cd ~/$DEST && npm install --no-audit --no-fund"
fi

say "prebuild: generating ios/ from app.json"
# --no-install because pod install runs below with the environment it needs; letting
# prebuild do it silently swallows the CocoaPods locale failure into a wall of output.
mac "cd ~/$DEST && npx expo prebuild -p ios --no-install"

# build:bare MUST run on macOS. `bare-pack --linked` bakes the host addon suffix into
# the bundle (.so on Linux, .dylib on macOS/iOS), so the committed bundle built on the
# dev box is Android-flavoured and an iOS build using it would not resolve its addons -
# which presents as ADDON_NOT_FOUND at launch, not as a build error.
say "building the UI and the macOS-flavoured bare bundle ON the Mac"
mac "cd ~/$DEST && npm run build:ui && npm run build:bare"

say "pod install"
mac "cd ~/$DEST/ios && pod install"

if [ -z "${SKIP_BUILD:-}" ]; then
  # CODE_SIGNING_ALLOWED=NO: a simulator build needs no identity, and asking for one
  # drags in the whole keychain-over-ssh problem for nothing.
  say "xcodebuild ($CONFIG, iphonesimulator) - this takes a while"
  mac "cd ~/$DEST/ios && xcodebuild -workspace $SCHEME.xcworkspace -scheme $SCHEME \
    -configuration $CONFIG -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' \
    -derivedDataPath build/dd CODE_SIGNING_ALLOWED=NO" > /tmp/pearcinema-ios-sim.log 2>&1 || {
      echo "BUILD FAILED. Errors:" >&2
      grep -oE "error: .{0,160}" /tmp/pearcinema-ios-sim.log | sort -u | head -12 >&2
      echo "(full log: /tmp/pearcinema-ios-sim.log)" >&2
      exit 1
    }
  echo "build ok"
fi

APP_PATH="~/$DEST/ios/build/dd/Build/Products/$CONFIG-iphonesimulator/$SCHEME.app"
mac "test -d $APP_PATH" || { echo "no .app at $APP_PATH - drop SKIP_BUILD" >&2; exit 1; }

say "the simulator"
# A NAMED, STANDING simulator rather than whatever is booted: two runs then mean the
# same device with the same data, so a pairing survives between builds.
UDID=$(mac "xcrun simctl list devices | grep -F '$SIM_NAME (' | grep -oE '[0-9A-F-]{36}' | head -1" || true)
if [ -z "$UDID" ]; then
  echo "  creating $SIM_NAME"
  RUNTIME=$(mac "xcrun simctl list runtimes | grep -oE 'com.apple.CoreSimulator.SimRuntime.iOS-[0-9-]+' | tail -1")
  UDID=$(mac "xcrun simctl create '$SIM_NAME' 'com.apple.CoreSimulator.SimDeviceType.${SIM_DEVICE// /-}' $RUNTIME")
fi
echo "  $SIM_NAME is $UDID"
mac "xcrun simctl boot $UDID 2>/dev/null || true"
mac "xcrun simctl bootstatus $UDID -b"

say "install and launch"
mac "xcrun simctl install $UDID $APP_PATH"
mac "xcrun simctl launch $UDID $BUNDLE_ID"

printf '\nRunning on %s. Useful next:\n' "$SIM_NAME"
printf '  ssh %s "xcrun simctl io %s screenshot ~/shot.png"\n' "$MAC" "$UDID"
printf '  ssh %s "xcrun simctl spawn %s log stream --predicate \x27processImagePath CONTAINS \\"%s\\"\x27"\n' "$MAC" "$UDID" "$SCHEME"
